-- MasterMounts: dungeon and raid teleports, by spell id.
--
-- The route is led by INSTANCE goals, and a player who has earned one
-- of these reaches that door instantly from anywhere. Modelling them is
-- worth more to a route than any number of flight paths.
--
-- NOTHING HERE IS ASSUMED TO BE OWNED. Every entry carries the spell id,
-- so the addon asks the client whether this character actually has it;
-- a teleport nobody earned never shortens anybody's route.
--
-- 76 teleports, each resolved against the shipped travel network to a
-- real map and coordinate. 0 more were DROPPED because their
-- destination did not resolve -- an unplaceable teleport is left out
-- rather than pointed at a guess.
--
-- Generated by tools/extract_dungeon_teleports.py. Do not hand-edit.
local _, MM = ...

MM.DungeonTeleports = {
	{spell=424153,name="Path of Ancient Horrors",place="Black Rook Hold",mapID=641,x=39.00,y=53.00,cooldown=28800,cast=10},
	{spell=393279,name="Path of Arcane Secrets",place="The Azure Vault",mapID=2024,x=38.00,y=64.00,cooldown=28800,cast=10},
	{spell=1254551,name="Path of Dark Dereliction",place="Seat of the Triumvirate",mapID=882,x=21.00,y=57.00,cooldown=28800,cast=10},
	{spell=1254572,name="Path of Devoted Magistry",place="Magisters' Terrace",mapID=2424,x=63.18,y=15.78,cooldown=28800,cast=10},
	{spell=410074,name="Path of Festering Rot",place="The Underrot",mapID=863,x=52.00,y=66.00,cooldown=28800,cast=10},
	{spell=424167,name="Path of Heart's Bane",place="Waycrest Manor",mapID=896,x=34.00,y=13.00,cooldown=28800,cast=10},
	{spell=445416,name="Path of Nerubian Ascension",place="City of Threads",mapID=2255,x=47.00,y=69.00,cooldown=28800,cast=10},
	{spell=424197,name="Path of Twisted Time",place="Dawn of the Infinites",mapID=2025,x=61.00,y=84.00,cooldown=28800,cast=10},
	{spell=1254555,name="Path of Unyielding Blight",place="Pit of Saron",mapID=118,x=52.00,y=89.00,cooldown=28800,cast=10},
	{spell=410080,name="Path of Wind's Domain",place="The Vortex Pinnacle",mapID=249,x=76.00,y=83.00,cooldown=28800,cast=10},
	{spell=1239155,name="Path of the All-Devouring",place="Manaforge Omega",mapID=2472,x=41.00,y=21.00,cooldown=28800,cast=10},
	{spell=445414,name="Path of the Arathi Flagship",place="The Dawnbreaker",mapID=2215,x=54.70,y=62.90,cooldown=28800,cast=10},
	{spell=354466,name="Path of the Ascendant",place="Spires of Ascension",mapID=1533,x=58.00,y=29.00,cooldown=28800,cast=10},
	{spell=467553,name="Path of the Azerite Refinery",place="The MOTHERLODE!!",mapID=862,x=40.00,y=72.00,cooldown=28800,cast=10,faction="Alliance"},
	{spell=467555,name="Path of the Azerite Refinery",place="The MOTHERLODE!!",mapID=862,x=56.00,y=60.00,cooldown=28800,cast=10,faction="Horde"},
	{spell=445418,name="Path of the Besieged Harbor",place="Siege of Boralus",mapID=895,x=72.00,y=23.00,cooldown=28800,cast=10,faction="Alliance"},
	{spell=464256,name="Path of the Besieged Harbor",place="Siege of Boralus",mapID=895,x=88.00,y=51.00,cooldown=28800,cast=10,faction="Horde"},
	{spell=432257,name="Path of the Bitter Legacy",place="Aberrus, the Shadowed Crucible",mapID=2133,x=48.00,y=11.00,cooldown=28800,cast=10},
	{spell=131228,name="Path of the Black Ox",place="Siege of Niuzao Temple",mapID=388,x=35.00,y=82.00,cooldown=28800,cast=10},
	{spell=159895,name="Path of the Bloodmaul",place="Bloodmaul Slag Mines",mapID=525,x=49.00,y=25.00,cooldown=28800,cast=10},
	{spell=159902,name="Path of the Burning Mountain",place="Upper Blackrock Spire",mapID=33,x=78.97,y=33.73,cooldown=28800,cast=10},
	{spell=1216786,name="Path of the Circuit Breaker",place="Operation: Floodgate",mapID=2214,x=42.09,y=39.48,cooldown=28800,cast=10},
	{spell=393256,name="Path of the Clutch Defender",place="Ruby Life Pools",mapID=2022,x=60.00,y=75.00,cooldown=28800,cast=10},
	{spell=445269,name="Path of the Corrupted Foundry",place="The Stonevault",mapID=2248,x=42.00,y=9.00,cooldown=28800,cast=10},
	{spell=354462,name="Path of the Courageous",place="The Necrotic Wake",mapID=1533,x=40.00,y=55.00,cooldown=28800,cast=10},
	{spell=159899,name="Path of the Crescent Moon",place="Shadowmoon Burial Grounds",mapID=539,x=32.00,y=42.00,cooldown=28800,cast=10},
	{spell=1254557,name="Path of the Crowning Pinnacle",place="Skyreach",mapID=542,x=35.00,y=33.00,cooldown=28800,cast=10},
	{spell=159900,name="Path of the Dark Rail",place="Grimrail Depot",mapID=543,x=55.00,y=32.00,cooldown=28800,cast=10},
	{spell=393272,name="Path of the Draconic Diploma",place="Algeth'ar Academy",mapID=2025,x=58.00,y=42.00,cooldown=28800,cast=10},
	{spell=410078,name="Path of the Earth-Warder",place="Neltharion's Lair",mapID=650,x=50.00,y=68.00,cooldown=28800,cast=10},
	{spell=1237215,name="Path of the Eco-Dome",place="Eco-Dome Al'dani",mapID=2472,x=43.80,y=4.47,cooldown=28800,cast=10},
	{spell=445443,name="Path of the Fallen Stormriders",place="The Rookery",mapID=2339,x=31.70,y=35.80,cooldown=28800,cast=10},
	{spell=373192,name="Path of the First Ones",place="Sepulcher of the First Ones",mapID=1970,x=81.00,y=53.00,cooldown=28800,cast=10},
	{spell=445440,name="Path of the Flaming Brewery",place="Cinderbrew Meadery",mapID=2248,x=76.00,y=45.00,cooldown=28800,cast=10},
	{spell=410071,name="Path of the Freebooter",place="Freehold",mapID=895,x=85.00,y=79.00,cooldown=28800,cast=10},
	{spell=1226482,name="Path of the Full House",place="Liberation of Undermine",mapID=2346,x=42.00,y=49.00,cooldown=28800,cast=10},
	{spell=424187,name="Path of the Golden Tomb",place="Atal'Dazar",mapID=862,x=44.00,y=39.00,cooldown=28800,cast=10},
	{spell=393766,name="Path of the Grand Magistrix",place="Court of Stars",mapID=680,x=51.00,y=65.00,cooldown=28800,cast=10},
	{spell=159896,name="Path of the Iron Prow",place="Iron Docks",mapID=543,x=45.00,y=13.00,cooldown=28800,cast=10},
	{spell=131204,name="Path of the Jade Serpent",place="Temple of the Jade Serpent",mapID=371,x=56.00,y=58.00,cooldown=28800,cast=10},
	{spell=445444,name="Path of the Light's Reverence",place="Priory of the Sacred Flame",mapID=2215,x=41.20,y=49.60,cooldown=28800,cast=10},
	{spell=354464,name="Path of the Misty Forest",place="Mists of Tirna Scithe",mapID=1565,x=35.00,y=54.00,cooldown=28800,cast=10},
	{spell=131222,name="Path of the Mogu King",place="Mogu'shan Palace",mapID=390,x=79.00,y=34.00,cooldown=28800,cast=10},
	{spell=131232,name="Path of the Necromancer",place="Scholomance",mapID=22,x=69.00,y=73.00,cooldown=28800,cast=10},
	{spell=424163,name="Path of the Nightmare Lord",place="Darkheart Thicket",mapID=641,x=59.00,y=31.00,cooldown=28800,cast=10},
	{spell=393276,name="Path of the Obsidian Hoard",place="Neltharus",mapID=2022,x=25.00,y=56.00,cooldown=28800,cast=10},
	{spell=354463,name="Path of the Plagued",place="Plaguefall",mapID=1536,x=59.00,y=65.00,cooldown=28800,cast=10},
	{spell=432254,name="Path of the Primal Prison",place="Vault of the Incarnates",mapID=2025,x=73.00,y=55.00,cooldown=28800,cast=10},
	{spell=393764,name="Path of the Proven Worth",place="Halls of Valor",mapID=634,x=68.00,y=66.00,cooldown=28800,cast=10},
	{spell=393267,name="Path of the Rotting Woods",place="Brackenhide Hollow",mapID=2024,x=11.00,y=48.00,cooldown=28800,cast=10},
	{spell=445417,name="Path of the Ruined City",place="Ara-Kara, City of Echoes",mapID=2255,x=49.00,y=81.00,cooldown=28800,cast=10},
	{spell=131231,name="Path of the Scarlet Blade",place="Scarlet Halls",mapID=18,x=82.00,y=33.00,cooldown=28800,cast=10},
	{spell=131229,name="Path of the Scarlet Mitre",place="Scarlet Monastery",mapID=18,x=82.00,y=33.00,cooldown=28800,cast=10},
	{spell=354468,name="Path of the Scheming Loa",place="De Other Side",mapID=1565,x=69.00,y=66.00,cooldown=28800,cast=10},
	{spell=432258,name="Path of the Scorching Dream",place="Amirdrassil, the Dream's Hope",mapID=2200,x=28.00,y=31.00,cooldown=28800,cast=10},
	{spell=373274,name="Path of the Scrappy Prince",place="Operation: Mechagon",mapID=1462,x=73.00,y=36.00,cooldown=28800,cast=10},
	{spell=131225,name="Path of the Setting Sun",place="Gate of the Setting Sun",mapID=390,x=16.00,y=74.00,cooldown=28800,cast=10},
	{spell=131206,name="Path of the Shado-Pan",place="Shado-Pan Monastery",mapID=379,x=37.00,y=48.00,cooldown=28800,cast=10},
	{spell=354465,name="Path of the Sinful Soul",place="Halls of Atonement",mapID=1525,x=78.46,y=49.05,cooldown=28800,cast=10},
	{spell=373190,name="Path of the Sire",place="Castle Nathria",mapID=1525,x=46.00,y=41.00,cooldown=28800,cast=10},
	{spell=159898,name="Path of the Skies",place="Skyreach",mapID=542,x=35.00,y=33.00,cooldown=28800,cast=10},
	{spell=354469,name="Path of the Stone Warden",place="Sanguine Depths",mapID=1525,x=51.00,y=30.00,cooldown=28800,cast=10},
	{spell=131205,name="Path of the Stout Brew",place="Stormstout Brewery",mapID=376,x=36.00,y=69.00,cooldown=28800,cast=10},
	{spell=367416,name="Path of the Streetwise Merchant",place="Tazavesh, the Veiled Market",mapID=2472,x=36.19,y=12.45,cooldown=28800,cast=10},
	{spell=424142,name="Path of the Tidehunter",place="Throne of the Tides",mapID=204,x=70.00,y=30.00,cooldown=28800,cast=10},
	{spell=393283,name="Path of the Titanic Reservoir",place="Halls of Infusion",mapID=2025,x=59.00,y=60.00,cooldown=28800,cast=10},
	{spell=373191,name="Path of the Tormented Soul",place="Sanctum of Domination",mapID=1543,x=69.00,y=31.00,cooldown=28800,cast=10},
	{spell=445424,name="Path of the Twilight Fortress",place="Grim Batol",mapID=241,x=19.00,y=54.00,cooldown=28800,cast=10},
	{spell=354467,name="Path of the Undefeated",place="Theater of Pain",mapID=1536,x=53.00,y=53.00,cooldown=28800,cast=10},
	{spell=159901,name="Path of the Verdant",place="The Everbloom",mapID=543,x=59.00,y=45.00,cooldown=28800,cast=10},
	{spell=159897,name="Path of the Vigilant",place="Auchindoun",mapID=535,x=46.00,y=74.00,cooldown=28800,cast=10},
	{spell=445441,name="Path of the Warding Candles",place="Darkflame Cleft",mapID=2214,x=56.00,y=21.00,cooldown=28800,cast=10},
	{spell=393222,name="Path of the Watcher's Legacy",place="Uldaman: Legacy of Tyr",mapID=15,x=41.00,y=10.00,cooldown=28800,cast=10},
	{spell=467546,name="Path of the Waterworks",place="Cinderbrew Meadery",mapID=2248,x=76.00,y=45.00,cooldown=28800,cast=10},
	{spell=1254400,name="Path of the Windrunners",place="Windrunner Spire",mapID=2395,x=35.48,y=78.83,cooldown=28800,cast=10},
	{spell=393262,name="Path of the Windswept Plains",place="The Nokhud Offensive",mapID=2023,x=61.00,y=39.00,cooldown=28800,cast=10},
}
