#!/usr/bin/env python3
"""Find vendor costs for mounts our records leave unpriced.

Records that carry no readable cost are ranked on a flat assumption. The local
collectible database states many of them exactly:

    mnt(68187, { itemID=49096, cost={{"c",3028,1}} })   -- 1 of currency 3028

Cost is read from the mount's OWN table, at its top level. A cost found inside
a nested child belongs to the child, and taking it would price a mount by
something else's requirements -- so the walker tracks depth rather than
grabbing the nearest match.

Only currency costs are taken. A gold cost is already handled from our own
source text, and an ITEM cost is a chain of its own that a single number
cannot honestly represent.
"""
import re
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ATT = pathlib.Path.home() / "Downloads/AllTheThings/db"
OUT = ROOT / "Data/_source/Data_99zj_AttCosts.lua"

DUMP = r'''
local MM={}
MM.AddMounts=function(t) MM._all=MM._all or {}; for _,r in ipairs(t) do MM._all[#MM._all+1]=r end end
MM.AddVendorLocations=function() end
MM.OverrideMount=function() end
local c=load(io.open("Data/Mounts.lua"):read("a"),"f","t"); pcall(c,"MM",MM)
for _,r in ipairs(MM._all or {}) do
  local cat = r.category or ""
  if (cat=="CURRENCY" or cat=="VENDOR" or cat=="TIMEWALKING" or cat=="PROFESSION")
     and r.obtainable and not (r.conditions and #r.conditions>0)
     and not r.acquire and not r.goldCost and (r.spellID or r.itemID) then
    print((r.name or "?") .. "\t" .. tostring(r.spellID or 0) .. "\t" .. tostring(r.itemID or 0))
  end
end
'''

OPEN = re.compile(r"\b(?:mnt|i)\((\d+)\s*,\s*\{")
COST = re.compile(r'cost=\{\{"c",(\d+),(\d+)\}\}')


def table_body(text, start):
    """Text of the table opened at `start` (index of its '{'), balanced."""
    depth, i, n = 0, start, len(text)
    while i < n:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i]
        i += 1
    return ""


def top_level_cost(body):
    """A cost declared by THIS table, not by one of its children."""
    depth, i, n = 0, 0, len(body)
    while i < n:
        ch = body[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        elif depth == 0:
            m = COST.match(body, i)
            if m:
                return int(m.group(1)), int(m.group(2))
        i += 1
    return None


def main():
    if not ATT.exists():
        sys.exit("collectible database not found: %s" % ATT)
    res = subprocess.run(["lua", "-e", DUMP], cwd=ROOT, capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit("could not read the database: " + res.stderr[:300])

    want = {}
    for line in res.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) == 3:
            name, spell, item = parts
            for v in (spell, item):
                if v != "0":
                    want[int(v)] = name

    order = sorted(ATT.rglob("*.lua"),
                   key=lambda p: (0 if "Standard" in p.parts else 1, str(p)))
    hits = {}
    for f in order:
        text = f.read_text(encoding="utf-8", errors="replace")
        if "cost={{" not in text:
            continue
        for m in OPEN.finditer(text):
            ident = int(m.group(1))
            name = want.get(ident)
            if not name or name in hits:
                continue
            got = top_level_cost(table_body(text, m.end() - 1))
            if got:
                hits[name] = got

    names = sorted(set(want.values()))
    print("  unpriced records with an id : %d" % len(names))
    print("  priced from the database    : %d" % len(hits))
    for nm in sorted(hits):
        cid, amt = hits[nm]
        print("     %-30s %6d x currency %d" % (nm[:30], amt, cid))
    print("  still unpriced              : %d" % (len(names) - len(hits)))

    out = [
        "-- MasterMounts: vendor costs taken from the local collectible database.",
        "--",
        "-- Read from each mount's OWN table at its top level. A cost inside a",
        "-- nested child belongs to the child, and taking it would price a mount",
        "-- by something else's requirements, so the walker tracks brace depth",
        "-- rather than grabbing the nearest match.",
        "--",
        "-- Currency only. Gold is already read from our own source text, and an",
        "-- item cost is a chain of its own that one number cannot honestly say.",
        "--",
        "-- %d records priced. The currency NAME is resolved by the client from"
        % len(hits),
        "-- the id, so a wrong id shows up as an unresolved condition rather than",
        "-- as a confident wrong number.",
        "--",
        "-- Generated by tools/extract_att_costs.py. Do not hand-edit.",
        "local _, MM = ...",
        "",
    ]
    for nm in sorted(hits):
        cid, amt = hits[nm]
        esc = nm.replace("\\", "\\\\").replace('"', '\\"')
        out.append('MM.OverrideMount("%s", { conditions = { '
                   '{ type = "CURRENCY", id = %d, amount = %d } } })'
                   % (esc, cid, amt))
    OUT.write_text("\n".join(out) + "\n")
    print("  wrote %s" % OUT.name)


if __name__ == "__main__":
    main()
