#!/usr/bin/env python3
"""Build Data/_source/Data_99zh_AchievementNames.lua from records' own prose.

42 ACHIEVEMENT records name their achievement only in prose, so their progress
cannot be read and each is ranked on a flat six-hour meta assumption. Where the
text names the achievement behind an EXPLICIT marker, that name becomes a real
condition and the client resolves it against its own 5,438-name index -- the
estimate then comes from criteria remaining instead of a guess.

ONLY EXPLICIT MARKERS. "Reward from the achievement X", "Achievement: X",
"Reward from X (...)". Free text is left alone: a name guessed out of a
sentence that happens to match a DIFFERENT real achievement would tell someone
to go and earn the wrong thing, which is worse than the flat assumption it
replaced. A name that resolves to nothing costs nothing -- the record is
exactly as unmodelled as it was.
"""
import re
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "Data/_source/Data_99zh_AchievementNames.lua"

DUMP = r'''
local MM={}
MM.AddMounts=function(t) MM._all=MM._all or {}; for _,r in ipairs(t) do MM._all[#MM._all+1]=r end end
MM.AddVendorLocations=function() end
MM.OverrideMount=function() end
local c=load(io.open("Data/Mounts.lua"):read("a"),"f","t"); pcall(c,"MM",MM)
for _,r in ipairs(MM._all or {}) do
  if r.category=="ACHIEVEMENT" then
    local modelled=false
    for _,cond in ipairs(r.conditions or {}) do
      if cond.type=="ACHIEVEMENT" then modelled=true break end
    end
    if not modelled then
      print((r.name or "?") .. "\t" .. ((r.source or ""):gsub("[\t\n]"," ")))
    end
  end
end
'''

PATTERNS = [
    r"[Aa]chievement:\s*([^—–.(]+)",
    r"[Rr]eward from the achievement\s+([^.(]+)",
    r"[Rr]eward from the\s+(.+?)\s+achievement",
    r"[Rr]eward from\s+([A-Z][^(.]+?)\s*\(",
    r"[Rr]eward from\s+([A-Z][^(.]+)\.",
]


def clean(s):
    if not s:
        return None
    s = s.strip().rstrip("—–- ").strip()
    # A fragment, a sentence, or something starting mid-clause is not a title.
    if len(s) < 4 or len(s) > 60 or s[0].islower():
        return None
    return s


def main():
    res = subprocess.run(["lua", "-e", DUMP], cwd=ROOT, capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit("could not read the database: " + res.stderr[:300])

    found, skipped = [], 0
    for line in res.stdout.splitlines():
        if "\t" not in line:
            continue
        name, source = line.split("\t", 1)
        title = None
        for pat in PATTERNS:
            m = re.search(pat, source)
            if m:
                title = clean(m.group(1))
                if title:
                    break
        if title:
            found.append((name, title))
        else:
            skipped += 1

    print("  achievement named behind an explicit marker : %d" % len(found))
    print("  named only in free text, left alone         : %d" % skipped)
    for n, t in found:
        print("     %-28s -> %s" % (n[:28], t))

    out = [
        "-- MasterMounts: achievement names lifted from each record's own prose.",
        "--",
        "-- These records name their achievement in a sentence, so nothing could",
        "-- read progress from them and each was ranked on a flat six-hour meta.",
        "-- With a name the client resolves the id from its own index and the",
        "-- estimate comes from criteria remaining instead.",
        "--",
        "-- ONLY WHERE AN EXPLICIT MARKER NAMES IT. %d records here; %d others"
        % (len(found), skipped),
        "-- name one only in free text and are left alone, because a title guessed",
        "-- out of a sentence that happens to match a DIFFERENT real achievement",
        "-- sends someone to earn the wrong thing -- worse than the assumption it",
        "-- would replace. A name that resolves to nothing costs nothing.",
        "--",
        "-- Generated by tools/extract_achievement_names.py. Do not hand-edit.",
        "local _, MM = ...",
        "",
    ]
    for name, title in sorted(found):
        e = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
        out.append('MM.OverrideMount("%s", { conditions = { '
                   '{ type = "ACHIEVEMENT", name = "%s" } } })' % (e(name), e(title)))

    OUT.write_text("\n".join(out) + "\n")
    print("  wrote %s" % OUT.name)


if __name__ == "__main__":
    main()
