#!/usr/bin/env python3
"""Build Data/FlightSeconds.lua from the local flight-time source.

Parses by STRUCTURE, not by assumed field order. The first attempt matched a
fixed `tag -> nodeID -> name -> neighbors` layout and silently captured 263 of
811 nodes -- two thirds of the data missing, with no error. Blocks in that file
do not all use the same field order.

This walks every `nodeID`, takes everything up to the next one as that node's
chunk, and reads whatever fields are present. It also PRINTS what it captured
against what is in the file, so an incomplete parse is visible rather than
silent.
"""
import re
import pathlib
import sys

SRC = pathlib.Path.home() / (
    "Downloads/ZygorGuidesViewer/Libs-Retail/LibTaxi-1.0/data.lua")
OUT = pathlib.Path(__file__).resolve().parent.parent / "Data/FlightSeconds.lua"


def main():
    if not SRC.exists():
        sys.exit("source not found: %s" % SRC)
    src = SRC.read_text(encoding="utf-8", errors="replace")
    body = src[src.index("data.flightcost"):]

    # NEGATIVE nodeIDs exist. `nodeID = -7` is Nighthaven, and a `(\d+)` pattern
    # cannot match a minus sign -- those blocks were not merely mis-parsed, they
    # were never seen, so their edges looked like data the source did not have.
    marks = [(m.start(), int(m.group(1)))
             for m in re.finditer(r"nodeID\s*=\s*(-?\d+)", body)]
    edges, names = {}, {}
    for i, (pos, nid) in enumerate(marks):
        end = marks[i + 1][0] if i + 1 < len(marks) else len(body)
        chunk = body[pos:end]
        nm = re.search(r'name\s*=\s*"([^"]*)"', chunk)
        if nm:
            names[nid] = nm.group(1)
        # BRACE COUNTING, not a non-greedy terminator.
        #
        # `neighbors = {(.*?)\n\s*\}` stops at the FIRST newline-then-brace, which
        # truncates any block whose closing brace is indented differently. That
        # quietly cost 22 nodes and 6 edges -- small enough to look like source
        # data being sparse rather than a parser being wrong.
        m = re.search(r"neighbors\s*=\s*\{", chunk)
        if not m:
            continue
        i, depth = m.end(), 1
        while i < len(chunk) and depth:
            c = chunk[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            i += 1
        inner = chunk[m.end():i - 1]
        # Negative keys here too -- a node with a negative id is somebody's
        # NEIGHBOUR as well as a node in its own right.
        d = {int(a): int(b)
             for a, b in re.findall(r"\[(-?\d+)\]\s*=\s*(\d+)", inner)
             if int(b) > 0}
        if d:
            # MERGE, do not overwrite. Ten nodeIDs appear twice in the source;
            # assigning would keep only the later block and silently drop the
            # earlier one's edges.
            if nid in edges:
                edges[nid].update(d)
            else:
                edges[nid] = d

    captured = sum(len(v) for v in edges.values())
    in_file = len(re.findall(r"\[-?\d+\]\s*=\s*\d+", body))
    oneway = sum(1 for a, d in edges.items()
                 for b in d if edges.get(b, {}).get(a) is None)

    print("  nodeIDs in source   : %d" % len(marks))
    print("  nodes with edges    : %d" % len(edges))
    print("  edges captured      : %d of %d in file" % (captured, in_file))
    print("  one-way edges       : %d" % oneway)

    head = [
        "-- MasterMounts: measured flight-path durations, by Blizzard taxi nodeID.",
        "--",
        "-- Seconds per hop between connected flight masters. These are OBSERVED",
        "-- trip times, not distance/speed estimates -- a flight follows a scripted",
        "-- path with turns, altitude changes and a takeoff, so a straight-line",
        "-- guess is wrong in both directions and never by a consistent factor.",
        "--",
        "-- %d nodes, %d edges, %d of them one-way (flight paths genuinely are)."
        % (len(edges), captured, oneway),
        "--",
        "-- Join key is the nodeID from C_TaxiMap.GetAllTaxiNodes, so this needs no",
        "-- name matching and cannot drift when a zone is renamed.",
        "--",
        "-- Generated by tools/extract_flight_times.py. Do not hand-edit.",
        "local _, MM = ...",
        "",
        "MM.FlightSeconds = {",
    ]
    # A NAME INDEX FROM THE SAME SOURCE.
    #
    # The router's Dijkstra keys on lowercase flight-master name; this data
    # keys on nodeID. Without a bridge the table loads and is never consulted
    # -- present, correct and inert, which is the worst of the three.
    #
    # Both halves come from the same records, so the mapping cannot disagree
    # with itself. Zygor-style names carry the zone ("Astranaar, Ashenvale");
    # the bare leading name is indexed too, because the client's own node names
    # do not include it.
    name_lines = ["", "MM.FlightNodeByName = {"]
    seen = {}

    # BEST-CONNECTED WINS a contested bare name, not first-seen.
    #
    # Several places appear twice -- "Astranaar" and "Astranaar, Ashenvale" --
    # as separate ids, and one of the pair is usually a stub with few or no
    # edges. First-wins handed the bare form to whichever id sorted lower, so
    # "Astranaar" could resolve to the stub and every route through it returned
    # "no path" while the real node sat right there fully connected.
    #
    # Edge count is the tiebreak because it is exactly the property that
    # matters: the node you can actually route through.
    def rank(nid):
        return len(edges.get(nid, ()))

    for nid in sorted(edges, key=lambda n: (-rank(n), n)):
        nm = names.get(nid)
        if not nm:
            continue
        for form in {nm.lower(), nm.split(",")[0].strip().lower()}:
            if form and form not in seen:
                seen[form] = nid
    for form in sorted(seen):
        name_lines.append('\t["%s"]=%d,' % (form.replace('"', '\\"'), seen[form]))
    name_lines.append("}")

    # THE REVERSE MAP, EMITTED DIRECTLY.
    #
    # Projecting the graph by INVERTING the name index lost 46 nodes and 263
    # edges: the index is first-wins, so when two flight masters share a name
    # form the second one has no entry to invert. Deriving a mapping from a
    # deliberately lossy one is the bug.
    #
    # This is written straight from the records, so every node that has a name
    # has a label, collisions included.
    name_lines += ["", "MM.FlightNodeName = {"]
    for nid in sorted(edges):
        nm = names.get(nid)
        if nm:
            name_lines.append('\t[%d]="%s",' % (nid, nm.replace('"', '\\"')))
    name_lines.append("}")

    body_lines = [
        "\t[%d]={%s}, -- %s" % (
            nid,
            ",".join("[%d]=%d" % (k, v) for k, v in sorted(edges[nid].items())),
            names.get(nid, "?"))
        for nid in sorted(edges)
    ]
    OUT.write_text("\n".join(head + body_lines + ["}"] + name_lines) + "\n")
    print("  name index          : %d forms" % len(seen))
    print("  wrote %s  %.0f KB" % (OUT.name, OUT.stat().st_size / 1024))


if __name__ == "__main__":
    main()
