#!/usr/bin/env python3
"""Build Data/_source/Data_99zg_GoldPrices.lua from the records' own source text.

WHAT THIS FIXES. 86 vendor mounts state a gold price in their source text --
"for about 10g" -- and carried no cost the planner could read, so each was
ranked on the 4-hour assumption used for anything unpriced. A 10 gold ram was
being costed like a raid grind, and ordered accordingly.

NOTHING IS INVENTED. The number is read out of the record's own source string;
records that say "sold for gold" without an amount are left alone rather than
guessed at. Names come from the database itself, so MM.OverrideMount cannot
fail silently on a name that does not exist.
"""
import re
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "Data/_source/Data_99zg_GoldPrices.lua"

DUMP = r'''
local MM={}
MM.AddMounts=function(t) MM._all=MM._all or {}; for _,r in ipairs(t) do MM._all[#MM._all+1]=r end end
MM.AddVendorLocations=function() end
MM.OverrideMount=function() end
local c=load(io.open("Data/Mounts.lua"):read("a"),"f","t"); pcall(c,"MM",MM)
for _,r in ipairs(MM._all or {}) do
  local paid=false
  for _,cond in ipairs(r.conditions or {}) do if cond.amount then paid=true end end
  local cat = r.category or ""
  if not paid and (cat=="VENDOR" or cat=="CURRENCY" or cat=="PROFESSION") then
    print((r.name or "?") .. "\t" .. ((r.source or ""):gsub("[\t\n]", " ")))
  end
end
'''

GOLD = re.compile(r"(\d[\d,]*)\s*g\b|(\d[\d,]*)\s*[Gg]old")


def main():
    res = subprocess.run(["lua", "-e", DUMP], cwd=ROOT,
                         capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit("could not read the database: " + res.stderr[:300])

    priced, stated_no_amount = [], 0
    for line in res.stdout.splitlines():
        if "\t" not in line:
            continue
        name, source = line.split("\t", 1)
        if not re.search(r"\d[\d,]*\s*g\b|[Gg]old", source):
            continue
        m = GOLD.search(source)
        if not m:
            stated_no_amount += 1
            continue
        amount = int((m.group(1) or m.group(2)).replace(",", ""))
        priced.append((name, amount))

    print("  records with a stated gold price : %d" % len(priced))
    print("  say 'gold' but name no amount    : %d (left alone)" % stated_no_amount)
    if priced:
        lo = min(a for _, a in priced)
        hi = max(a for _, a in priced)
        print("  range                            : %dg to %sg" % (lo, "{:,}".format(hi)))

    out = [
        "-- MasterMounts: gold prices, read from each record's own source text.",
        "--",
        "-- These mounts state a price -- \"for about 10g\" -- and carried no cost",
        "-- the planner could read, so every one was ranked on the flat assumption",
        "-- used for anything unpriced. A 10 gold ram was costed like a raid grind",
        "-- and ordered like one.",
        "--",
        "-- Gold is not a currency id and not a time. What the planner does with it",
        "-- is ask the client whether this character can already afford it: if it",
        "-- can, the only real cost is getting there and clicking. If it cannot,",
        "-- the pessimistic assumption stands, because how long gold takes to earn",
        "-- is not something this addon can know.",
        "--",
        "-- %d records. Anything that says 'sold for gold' without naming an amount"
        % len(priced),
        "-- is left alone rather than guessed at.",
        "--",
        "-- Generated by tools/extract_gold_prices.py. Do not hand-edit.",
        "local _, MM = ...",
        "",
    ]
    for name, amount in sorted(priced):
        esc = name.replace("\\", "\\\\").replace('"', '\\"')
        out.append('MM.OverrideMount("%s", { goldCost = %d })' % (esc, amount))

    OUT.write_text("\n".join(out) + "\n")
    print("  wrote %s  %.0f KB" % (OUT.name, OUT.stat().st_size / 1024))


if __name__ == "__main__":
    main()
