#!/usr/bin/env python3
"""Put real npc ids on drop sources that are only named.

Same shape as extract_quest_ids.py, and for the same reason: the client offers
no reverse npc-name -> id lookup, but the local guide data ships a complete
npcID -> name table.

An id is written ONLY where exactly one npc carries that name. Boss names are
routinely reused across difficulties and expansions -- "Garrosh Hellscream" is
eight different ids -- and picking one would point the arrow at the wrong
encounter, so every ambiguous name is left alone and counted.

Writes Data/_source/Data_99zl_NpcIDs.lua. Do not hand-edit that file.
"""
import collections
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
NPCS = (pathlib.Path.home()
        / "Downloads/ZygorGuidesViewer/Localization-Retail/NPCs_enUS.lua")
OUT = ROOT / "Data/_source/Data_99zl_NpcIDs.lua"


def npc_index():
    if not NPCS.exists():
        sys.exit("npc name source not found: %s" % NPCS)
    idx = collections.defaultdict(set)
    text = NPCS.read_text(encoding="utf-8", errors="replace")
    for nid, name in re.findall(r'\[(\d+)\]\s*=\s*"((?:[^"\\]|\\.)*)"', text):
        idx[name.strip().lower()].add(int(nid))
    return idx


def named_npcs_without_ids():
    """Loaded from the built database, so overrides are already applied."""
    lua = r'''
local MM = {}
local recs = {}
MM.AddMounts = function(t) for _, r in ipairs(t) do recs[#recs+1] = r end end
setmetatable(MM, { __index = function() return function() end end })
assert(loadfile("%s"))("MasterMounts", MM)
local seen = {}
for _, r in ipairs(recs) do
  local n = r.npc
  if type(n) == "table" and n.name and not n.id and not seen[n.name] then
    seen[n.name] = true
    print(n.name)
  end
end
''' % (ROOT / "Data/Mounts.lua")
    p = subprocess.run(["lua", "-"], input=lua, capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit("could not load the database: %s" % p.stderr.strip())
    return [l for l in p.stdout.splitlines() if l.strip()]


def lua_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    idx = npc_index()
    print("  npc names indexed        : %d" % len(idx))
    names = named_npcs_without_ids()
    print("  npcs named with no id    : %d" % len(names))

    resolved, ambiguous, unmatched = [], [], 0
    for name in names:
        ids = idx.get(name.strip().lower())
        if not ids:
            unmatched += 1
        elif len(ids) > 1:
            ambiguous.append((name, sorted(ids)))
        else:
            resolved.append((name, next(iter(ids))))

    resolved.sort()
    print("  resolved exactly         : %d" % len(resolved))
    print("  left alone (ambiguous)   : %d" % len(ambiguous))
    print("  left alone (no match)    : %d" % unmatched)

    body = [
        "-- MasterMounts: npc ids for drop sources that were only named.",
        "--",
        "-- The client has no reverse npc-name to id lookup. The local guide",
        "-- data does, so an exact name match supplies the id and the arrow can",
        "-- point at the encounter rather than the zone.",
        "--",
        "-- ONLY WHERE EXACTLY ONE NPC CARRIES THAT NAME. %d matched; %d names"
        % (len(resolved), len(ambiguous)),
        "-- belong to more than one npc and %d match nothing -- both left alone."
        % unmatched,
        "-- \"Garrosh Hellscream\" is eight ids across four encounters; choosing",
        "-- one points the player at the wrong fight.",
        "--",
        "-- Keyed by NPC, not by mount: one source feeds several mounts, and a",
        "-- per-mount override would replace the whole npc table.",
        "--",
        "-- Ambiguous, and deliberately absent:",
    ]
    for name, ids in sorted(ambiguous):
        body.append("--   %-32s %s" % (name, ", ".join(str(i) for i in ids[:6])))
    body += [
        "--",
        "-- Generated by tools/extract_npc_ids.py. Do not hand-edit.",
        "local _, MM = ...",
        "",
    ]
    for name, nid in resolved:
        body.append('MM.SetNpcID("%s", %d)' % (lua_escape(name), nid))
    body.append("")
    OUT.write_text("\n".join(body), encoding="utf-8")
    print("  wrote %s (%d ids)" % (OUT.name, len(resolved)))


if __name__ == "__main__":
    main()
