-- MasterMounts: NPC coordinates from Wowhead (authoritative).
-- Resolved per NPC rather than per zone, which keeps faction-split
-- vendors correct -- each faction's quartermaster resolves separately.
-- NOT written: ambiguous names, multi-zone NPCs, and spawns carrying no
-- uiMapId (Wowhead's outer key is its own zone id, not the WoW map id).
-- See FAILURES.txt for everything skipped and why.
local _, MM = ...

MM.OverrideMount("Phalynx of Humility", { zone = { name = "Bastion", mapID = 1533, x = 67.4, y = 15.0 } }) -- Adjutant Galos (npc=174937, wowhead)
MM.OverrideMount("Swift Frostwolf", { zone = { name = "Warspear, Ashran", mapID = 624, x = 53.5, y = 62.1 } }) -- Beska Redtusk (npc=86036, zygor)
MM.OverrideMount("Liberated Slyvern", { zone = { mapID = 2024, x = 28.92, y = 47.41 } }) -- Breezebiter (npc=195353, rarescanner)
MM.OverrideMount("Crimson Silvermoon Hawkstrider", { zone = { name = "Eversong Woods", mapID = 2395, x = 43.4, y = 47.4 } }) -- Caeris Fairdawn (npc=240838, wowhead)
MM.OverrideMount("Fiery Dragonhawk", { zone = { name = "Eversong Woods", mapID = 2395, x = 43.4, y = 47.4 } }) -- Caeris Fairdawn (npc=240838, wowhead)
MM.OverrideMount("Preyhunter's Fury", { zone = { name = "Silvermoon City", mapID = 2393, x = 55.8, y = 65.8 } }) -- Construct V'anore (npc=252956, wowhead)
MM.OverrideMount("Stormwind Steed", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 19.2 } }) -- Corporal Arthur Flew (npc=33307, zygor)
MM.OverrideMount("Swift Gray Steed", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 19.2 } }) -- Corporal Arthur Flew (npc=33307, zygor)
MM.OverrideMount("Mosshide Riverwallow", { zone = { name = "Stormshield, Ashran", mapID = 622, x = 50.4, y = 61.72 } }) -- Dawn-Seeker Krek (npc=86391, zygor)
MM.OverrideMount("Slumbering Worldsnail", { zone = { name = "The Waking Shores", mapID = 2022, x = 34.8, y = 46.6 } }) -- Dealer Vexil (npc=193310, wowhead)
MM.OverrideMount("Ironforge Ram", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 19.4 } }) -- Derrick Brindlebeard (npc=33310, wowhead)
MM.OverrideMount("Swift Violet Ram", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 19.4 } }) -- Derrick Brindlebeard (npc=33310, wowhead)
MM.OverrideMount("Thunder Bluff Kodo", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 24.4 } }) -- Doru Thunderhorn (npc=33556, wowhead)
MM.OverrideMount("Great Golden Kodo", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 24.4 } }) -- Doru Thunderhorn (npc=33556, wowhead)
MM.OverrideMount("Tawny Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Blue Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Green Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Swift Red Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Swift Green Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Swift Yellow Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Swift Purple Wind Rider", { zone = { name = "Orgrimmar", mapID = 85, x = 48.0, y = 58.5 } }) -- Drakma (npc=44918, zygor)
MM.OverrideMount("Forsaken Warhorse", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 24.0 } }) -- Eliza Killian (npc=33555, wowhead)
MM.OverrideMount("White Skeletal Warhorse", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 24.0 } }) -- Eliza Killian (npc=33555, wowhead)
MM.OverrideMount("Lord of the Corpseflies", { zone = { name = "Korthia", mapID = 1961, x = 59.4, y = 42.4 } }) -- Fleshwing (npc=180042, wowhead)
MM.OverrideMount("Orgrimmar Wolf", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 24.2 } }) -- Freka Bloodaxe (npc=33553, wowhead)
MM.OverrideMount("Swift Burgundy Wolf", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 24.2 } }) -- Freka Bloodaxe (npc=33553, wowhead)
MM.OverrideMount("Predatory Plagueroc", { zone = { name = "Maldraxxus", mapID = 1536, x = 31.4, y = 35.4 } }) -- Gieger (npc=162741, wowhead)
MM.OverrideMount("Spinemaw Gladechewer", { zone = { name = "Ardenweald", mapID = 1565, x = 26.6, y = 55.2 } }) -- Gormtamer Tizo (npc=164107, wowhead)
MM.OverrideMount("Blue Marsh Hopper", { zone = { name = "Nazmir", mapID = 863, x = 70.8, y = 56.4 } }) -- Gottum (npc=148810, wowhead)
MM.OverrideMount("Green Marsh Hopper", { zone = { name = "Nazmir", mapID = 863, x = 70.8, y = 56.4 } }) -- Gottum (npc=148810, wowhead)
MM.OverrideMount("Yellow Marsh Hopper", { zone = { name = "Nazmir", mapID = 863, x = 70.8, y = 56.4 } }) -- Gottum (npc=148810, wowhead)
MM.OverrideMount("Azure Skitterfly", { zone = { name = "The Waking Shores", mapID = 2022, x = 47.6, y = 83.2 } }) -- Granpap Whiskers (npc=187408, wowhead)
MM.OverrideMount("Tamed Skitterfly", { zone = { name = "The Waking Shores", mapID = 2022, x = 47.6, y = 83.2 } }) -- Granpap Whiskers (npc=187408, wowhead)
MM.OverrideMount("Gray Kodo", { zone = { name = "Mulgore", mapID = 7, x = 47.6, y = 58.0 } }) -- Harb Clawhoof (npc=3685, zygor)
MM.OverrideMount("Brown Kodo", { zone = { name = "Mulgore", mapID = 7, x = 47.6, y = 58.0 } }) -- Harb Clawhoof (npc=3685, zygor)
MM.OverrideMount("Great White Kodo", { zone = { name = "Mulgore", mapID = 7, x = 47.6, y = 58.0 } }) -- Harb Clawhoof (npc=3685, zygor)
MM.OverrideMount("Great Gray Kodo", { zone = { name = "Mulgore", mapID = 7, x = 47.6, y = 58.0 } }) -- Harb Clawhoof (npc=3685, zygor)
MM.OverrideMount("Great Brown Kodo", { zone = { name = "Mulgore", mapID = 7, x = 47.6, y = 58.0 } }) -- Harb Clawhoof (npc=3685, zygor)
MM.OverrideMount("White Kodo", { zone = { name = "Mulgore", mapID = 7, x = 47.6, y = 58.0 } }) -- Harb Clawhoof (npc=3685, zygor)
MM.OverrideMount("Deepstar Aurelid", { zone = { name = "Zereth Mortis", mapID = 1970, x = 51.4, y = 74.2 } }) -- Hirukon (npc=180978, wowhead)
MM.OverrideMount("Hopecrusher Gargon", { zone = { name = "Revendreth", mapID = 1525, x = 51.4, y = 52.4 } }) -- Hopecrusher (npc=166679, wowhead)
MM.OverrideMount("Arboreal Gulper", { zone = { mapID = 1565, x = 32.42, y = 30.26 } }) -- Humon'gozz (npc=164112, rarescanner)
MM.OverrideMount("Exodar Elekk", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 19.2 } }) -- Irisee (npc=33657, wowhead)
MM.OverrideMount("Great Red Elekk", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 19.2 } }) -- Irisee (npc=33657, wowhead)
MM.OverrideMount("Pinto", { zone = { name = "Stormwind City", mapID = 84, x = 77.0, y = 67.8 } }) -- Katie Stokx (npc=43694, zygor)
MM.OverrideMount("Chestnut Mare", { zone = { name = "Stormwind City", mapID = 84, x = 77.0, y = 67.8 } }) -- Katie Stokx (npc=43694, zygor)
MM.OverrideMount("Swift Palomino", { zone = { name = "Stormwind City", mapID = 84, x = 77.0, y = 67.8 } }) -- Katie Stokx (npc=43694, zygor)
MM.OverrideMount("Swift White Steed", { zone = { name = "Stormwind City", mapID = 84, x = 77.0, y = 67.8 } }) -- Katie Stokx (npc=43694, zygor)
MM.OverrideMount("Swift Brown Steed", { zone = { name = "Stormwind City", mapID = 84, x = 77.0, y = 67.8 } }) -- Katie Stokx (npc=43694, zygor)
MM.OverrideMount("Striped Frostsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Spotted Frostsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Striped Nightsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Striped Dawnsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Swift Mistsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Swift Frostsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Swift Stormsaber", { zone = { name = "Darnassus", mapID = 89, x = 42.5, y = 32.69 } }) -- Lelanai (npc=4730, zygor)
MM.OverrideMount("Black War Steed", { zone = { name = "Stormwind City", mapID = 84, x = 76.2, y = 65.5 } }) -- Lieutenant Karter (npc=12783, zygor)
MM.OverrideMount("Black War Ram", { zone = { name = "Stormwind City", mapID = 84, x = 76.2, y = 65.5 } }) -- Lieutenant Karter (npc=12783, zygor)
MM.OverrideMount("Black Battlestrider", { zone = { name = "Stormwind City", mapID = 84, x = 76.2, y = 65.5 } }) -- Lieutenant Karter (npc=12783, zygor)
MM.OverrideMount("Black War Tiger", { zone = { name = "Stormwind City", mapID = 84, x = 76.2, y = 65.5 } }) -- Lieutenant Karter (npc=12783, zygor)
MM.OverrideMount("Amani Blessed Bear", { zone = { name = "Zul'Aman", mapID = 2437, x = 45.8, y = 65.8 } }) -- Magovu (npc=240279, wowhead)
MM.OverrideMount("Amani Windcaller", { zone = { name = "Zul'Aman", mapID = 2437, x = 45.8, y = 65.8 } }) -- Magovu (npc=240279, wowhead)
MM.OverrideMount("Crimson Shardhide", { zone = { name = "Korthia", mapID = 1961, x = 44.4, y = 29.4 } }) -- Malbog (npc=179684, wowhead)
MM.OverrideMount("Blue Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Red Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Green Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Unpainted Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Swift Yellow Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Swift White Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Swift Green Mechanostrider", { zone = { name = "Dun Morogh", mapID = 27, x = 56.2, y = 46.2 } }) -- Milli Featherwhistle (npc=7955, zygor)
MM.OverrideMount("Vivid Chloroceros", { zone = { name = "Harandar", mapID = 2413, x = 49.2, y = 54.4 } }) -- Mothkeeper Wew'tam (npc=251259, wowhead)
MM.OverrideMount("Elder Glowmite", { zone = { name = "Harandar", mapID = 2413, x = 49.2, y = 54.4 } }) -- Mothkeeper Wew'tam (npc=251259, wowhead)
MM.OverrideMount("Fierce Grimlynx", { zone = { name = "Harandar", mapID = 2413, x = 51.0, y = 50.8 } }) -- Naynar (npc=240407, wowhead)
MM.OverrideMount("Cerulean Sporeglider", { zone = { name = "Harandar", mapID = 2413, x = 51.0, y = 50.8 } }) -- Naynar (npc=240407, wowhead)
MM.OverrideMount("Vicious Kaldorei Warsaber", { zone = { name = "Stormwind City", mapID = 84, x = 76.8, y = 65.4 } }) -- Necrolord Sipe (npc=73190, wowhead)
MM.OverrideMount("Vicious War Mechanostrider", { zone = { name = "Stormwind City", mapID = 84, x = 76.8, y = 65.4 } }) -- Necrolord Sipe (npc=73190, wowhead)
MM.OverrideMount("Vicious War Elekk", { zone = { name = "Stormwind City", mapID = 84, x = 76.8, y = 65.4 } }) -- Necrolord Sipe (npc=73190, wowhead)
MM.OverrideMount("Vicious War Lion", { zone = { name = "Stormwind City", mapID = 84, x = 76.8, y = 65.4 } }) -- Necrolord Sipe (npc=73190, wowhead)
MM.OverrideMount("Vicious Black Warsaber", { zone = { name = "Stormwind City", mapID = 84, x = 76.8, y = 65.4 } }) -- Necrolord Sipe (npc=73190, wowhead)
MM.OverrideMount("Vicious White Warsaber", { zone = { name = "Stormwind City", mapID = 84, x = 76.8, y = 65.4 } }) -- Necrolord Sipe (npc=73190, wowhead)
MM.OverrideMount("Gorespine", { zone = { name = "Maldraxxus", mapID = 1536, x = 65.4, y = 35.2 } }) -- Nerissa Heartless (npc=162690, wowhead)
MM.OverrideMount("Timber Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Dire Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Brown Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Swift Gray Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Swift Brown Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Swift Timber Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Black Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Gray Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 61.0, y = 35.2 } }) -- Ogunaro Wolfrunner (npc=3362, wowhead)
MM.OverrideMount("Boulder Hauler", { zone = { name = "Zaralek Cavern", mapID = 2133, x = 58.0, y = 53.8 } }) -- Ponzo (npc=204693, wowhead)
MM.OverrideMount("Black War Wolf", { zone = { name = "Orgrimmar", mapID = 85, x = 41.8, y = 72.5 } }) -- Raider Bork (npc=12796, zygor)
MM.OverrideMount("Black War Kodo", { zone = { name = "Orgrimmar", mapID = 85, x = 41.8, y = 72.5 } }) -- Raider Bork (npc=12796, zygor)
MM.OverrideMount("Black War Raptor", { zone = { name = "Orgrimmar", mapID = 85, x = 41.8, y = 72.5 } }) -- Raider Bork (npc=12796, zygor)
MM.OverrideMount("Red Skeletal Warhorse", { zone = { name = "Orgrimmar", mapID = 85, x = 41.8, y = 72.5 } }) -- Raider Bork (npc=12796, zygor)
MM.OverrideMount("Gnomeregan Mechanostrider", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 19.4 } }) -- Rillie Spindlenut (npc=33650, wowhead)
MM.OverrideMount("Turbostrider", { zone = { name = "Icecrown", mapID = 118, x = 76.4, y = 19.4 } }) -- Rillie Spindlenut (npc=33650, wowhead)
MM.OverrideMount("Darnassian Nightsaber", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 19.2 } }) -- Rook Hawkfist (npc=33653, wowhead)
MM.OverrideMount("Swift Moonsaber", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 19.2 } }) -- Rook Hawkfist (npc=33653, wowhead)
MM.OverrideMount("Darkspear Raptor", { zone = { name = "Icecrown", mapID = 118, x = 76.0, y = 24.4 } }) -- Samamba (npc=33554, wowhead)
MM.OverrideMount("Swift Purple Raptor", { zone = { name = "Icecrown", mapID = 118, x = 76.0, y = 24.4 } }) -- Samamba (npc=33554, wowhead)
MM.OverrideMount("Skullripper", { zone = { mapID = 943, x = 66.33, y = 57.54 } }) -- Skullripper (npc=142312, rarescanner)
MM.OverrideMount("Mastercraft Gravewing", { zone = { name = "Korthia", mapID = 1961, x = 45.4, y = 78.2 } }) -- Stygian Stonecrusher (npc=179985, wowhead)
MM.OverrideMount("Bonehoof Tauralus", { zone = { name = "Maldraxxus", mapID = 1536, x = 44.0, y = 50.4 } }) -- Tahonta (npc=162586, wowhead)
MM.OverrideMount("Iskaara Trader's Ottuk", { zone = { name = "The Azure Span", mapID = 2024, x = 14.0, y = 49.6 } }) -- Tattukiaka (npc=199448, wowhead)
MM.OverrideMount("Silvermoon Hawkstrider", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 23.8 } }) -- Trellis Morningsun (npc=33557, wowhead)
MM.OverrideMount("Swift Red Hawkstrider", { zone = { name = "Icecrown", mapID = 118, x = 76.2, y = 23.8 } }) -- Trellis Morningsun (npc=33557, wowhead)
MM.OverrideMount("Brown Horse", { zone = { name = "Wetlands", mapID = 56, x = 9.19, y = 56.4 } }) -- Unger Statforth (npc=1460, zygor)
MM.OverrideMount("Gray Ram", { zone = { name = "Dun Morogh", mapID = 27, x = 70.6, y = 48.8 } }) -- Veron Amberstill (npc=1261, zygor)
MM.OverrideMount("White Ram", { zone = { name = "Dun Morogh", mapID = 27, x = 70.6, y = 48.8 } }) -- Veron Amberstill (npc=1261, zygor)
MM.OverrideMount("Brown Ram", { zone = { name = "Dun Morogh", mapID = 27, x = 70.6, y = 48.8 } }) -- Veron Amberstill (npc=1261, zygor)
MM.OverrideMount("Swift Brown Ram", { zone = { name = "Dun Morogh", mapID = 27, x = 70.6, y = 48.8 } }) -- Veron Amberstill (npc=1261, zygor)
MM.OverrideMount("Swift Gray Ram", { zone = { name = "Dun Morogh", mapID = 27, x = 70.6, y = 48.8 } }) -- Veron Amberstill (npc=1261, zygor)
MM.OverrideMount("Swift White Ram", { zone = { name = "Dun Morogh", mapID = 27, x = 70.6, y = 48.8 } }) -- Veron Amberstill (npc=1261, zygor)
MM.OverrideMount("Dusty Rockhide", { zone = { name = "Stormshield, Ashran", mapID = 622, x = 46.5, y = 76.3 } }) -- Vindicator Nuurem (npc=85932, zygor)
MM.OverrideMount("Hulking Deathroc", { zone = { mapID = 1536, x = 58.59, y = 74.21 } }) -- Violet Mistake (npc=157309, rarescanner)
MM.OverrideMount("Blisterback Bloodtusk", { zone = { mapID = 1536, x = 33.71, y = 80.16 } }) -- Warbringer Mal'Korak (npc=162819, rarescanner)
MM.OverrideMount("Forsworn Aquilon", { zone = { mapID = 1961, x = 56.87, y = 32.37 } }) -- Wild Worldcracker (npc=180032, rarescanner)
MM.OverrideMount("Maddened Chaosrunner", { zone = { mapID = 882, x = 55.53, y = 60.15 } }) -- Wrangler Kravos (npc=126852, rarescanner)
MM.OverrideMount("Emerald Raptor", { zone = { name = "Durotar", mapID = 1, x = 55.2, y = 75.5 } }) -- Zjolnir (npc=7952, zygor)
MM.OverrideMount("Turquoise Raptor", { zone = { name = "Durotar", mapID = 1, x = 55.2, y = 75.5 } }) -- Zjolnir (npc=7952, zygor)
MM.OverrideMount("Violet Raptor", { zone = { name = "Durotar", mapID = 1, x = 55.2, y = 75.5 } }) -- Zjolnir (npc=7952, zygor)
MM.OverrideMount("Swift Blue Raptor", { zone = { name = "Durotar", mapID = 1, x = 55.2, y = 75.5 } }) -- Zjolnir (npc=7952, zygor)
MM.OverrideMount("Swift Olive Raptor", { zone = { name = "Durotar", mapID = 1, x = 55.2, y = 75.5 } }) -- Zjolnir (npc=7952, zygor)
MM.OverrideMount("Swift Orange Raptor", { zone = { name = "Durotar", mapID = 1, x = 55.2, y = 75.5 } }) -- Zjolnir (npc=7952, zygor)
