-- Master Mounts: baked-in flight point locations. GENERATED.
--
-- A starting point, not the truth. C_TaxiMap is authoritative and knows what
-- THIS character has unlocked, but it only answers while a flight master's map
-- is open -- so on a fresh install, standing in the world, we would have
-- nothing at all and every zone-only goal would route to a zone centroid.
--
-- So this ships as the floor. The moment the player opens any flight master,
-- the live API overwrites it for every zone at once and the saved copy is what
-- gets used from then on. Blizzard moving a flight point costs one taxi visit
-- to correct, and costs nothing until then.
--
-- Coordinates are zone-relative 0-100, matching every other record here.
-- faction: "A" Alliance only, "H" Horde only, "B" either.
local _, MM = ...

MM.FlightPointData = {
	["abyssal depths"] = {
		{ name = "Darkbreak Cove", npc = "Swift Seahorse", x = 56.90, y = 75.53, faction = "A", continent = 13 },
		{ name = "Tenebrous Cavern", npc = "Swift Seahorse", x = 53.88, y = 59.62, faction = "H", continent = 13 },
	},
	["amirdrassil"] = {
		{ name = "Bel'ameth", npc = "Leora", x = 50.23, y = 55.93, faction = "B", continent = 1978 },
	},
	["antoran wastes"] = {
		{ name = "Vindicaar, Antoran Wastes", npc = "", x = 32.32, y = 56.57, faction = "B", continent = 994 },
		{ name = "Hope's Landing, Antoran Wastes", npc = "", x = 72.96, y = 50.52, faction = "B", continent = 994 },
		{ name = "The Veiled Den, Antoran Wastes", npc = "", x = 70.59, y = 25.48, faction = "B", continent = 994 },
		{ name = "Light's Purchase, Antoran Wastes", npc = "", x = 72.64, y = 76.17, faction = "B", continent = 994 },
	},
	["arathi highlands"] = {
		{ name = "Refuge Pointe", npc = "Cedrik Prose", x = 39.89, y = 47.35, faction = "A", continent = 13 },
		{ name = "Galen's Fall", npc = "Rhoda Bowers", x = 13.31, y = 34.82, faction = "H", continent = 13 },
		{ name = "Hammerfall", npc = "Urda", x = 68.16, y = 33.39, faction = "H", continent = 13 },
	},
	["ardenweald"] = {
		{ name = "Tirna Vaal", npc = "Lanra", x = 63.46, y = 37.56, faction = "B", continent = 1550 },
		{ name = "Hibernal Hollow", npc = "Na'lor", x = 60.35, y = 53.49, faction = "B", continent = 1550 },
		{ name = "Claw's Edge", npc = "V'kerra", x = 51.30, y = 71.31, faction = "B", continent = 1550 },
		{ name = "Refugee Camp", npc = "Derwynnthlmn", x = 49.35, y = 51.82, faction = "B", continent = 1550 },
		{ name = "Glitterfall Basin", npc = "Dwyl'ir", x = 51.42, y = 34.52, faction = "B", continent = 1550 },
		{ name = "Root-Home", npc = "Tishereenelee", x = 35.14, y = 51.71, faction = "B", continent = 1550 },
		{ name = "Heart of the Forest", npc = "Ceridwyn", x = 46.26, y = 50.81, faction = "B", continent = 1550 },
	},
	["ashenvale"] = {
		{ name = "Astranaar", npc = "Daelyshia", x = 34.41, y = 47.99, faction = "A", continent = 12 },
		{ name = "Blackfathom Camp", npc = "Solais", x = 18.14, y = 20.59, faction = "A", continent = 12 },
		{ name = "Forest Song", npc = "Suralais Farwind", x = 85.09, y = 43.45, faction = "A", continent = 12 },
		{ name = "Stardust Spire", npc = "Myre Moonglide", x = 35.02, y = 72.07, faction = "A", continent = 12 },
		{ name = "Hellscream's Watch", npc = "Thraka", x = 38.08, y = 42.22, faction = "H", continent = 12 },
		{ name = "Silverwind Refuge", npc = "Wind Tamer Shoshok", x = 49.29, y = 65.25, faction = "H", continent = 12 },
		{ name = "Splintertree Post", npc = "Vhulgra", x = 73.18, y = 61.59, faction = "H", continent = 12 },
		{ name = "Zoram'gar Outpost", npc = "Andruk", x = 11.17, y = 34.43, faction = "H", continent = 12 },
		{ name = "Astranaar", npc = "Sentinel Luara", x = 34.75, y = 48.53, faction = "A", continent = 12 },
		{ name = "Maestra's Post", npc = "Sentinel Avana", x = 26.80, y = 35.99, faction = "A", continent = 12 },
	},
	["atal aman m/1"] = {
		{ name = "Atal'Aman", npc = "Eagletender Po'vari", x = 39.79, y = 40.79, faction = "B", continent = 13 },
	},
	["azj-kahet"] = {
		{ name = "Wildcamp Or'lay", npc = "Courier Nailen", x = 23.14, y = 51.14, faction = "B", continent = 2274 },
		{ name = "Faerin's Advance", npc = "Courier Aidal", x = 60.00, y = 18.70, faction = "B", continent = 2274 },
		{ name = "Weaver's Lair", npc = "Wings of the Widow", x = 56.87, y = 47.04, faction = "B", continent = 2274 },
		{ name = "Wildcamp Ul'ar", npc = "Courier Lyan", x = 44.49, y = 67.48, faction = "B", continent = 2274 },
		{ name = "Mmarl", npc = "Roughrider Tany", x = 76.84, y = 64.45, faction = "B", continent = 2274 },
	},
	["azshara"] = {
		{ name = "Bilgewater Harbor", npc = "Kroum", x = 52.92, y = 49.86, faction = "H", continent = 12 },
		{ name = "Northern Rocketway", npc = "Blitz Blastospazz", x = 66.50, y = 21.01, faction = "H", continent = 12 },
		{ name = "Southern Rocketway", npc = "Friz Groundspin", x = 51.49, y = 74.29, faction = "H", continent = 12 },
		{ name = "Valormok", npc = "Kroum", x = 14.35, y = 65.02, faction = "H", continent = 12 },
	},
	["azsuna"] = {
		{ name = "Azurewing Repose", npc = "Dagrona", x = 48.45, y = 28.07, faction = "B", continent = 619 },
		{ name = "Challiane's Terrace", npc = "Stagtamer Maliana", x = 40.81, y = 9.02, faction = "B", continent = 619 },
		{ name = "Felblaze Ingress", npc = "Adept Sunwing", x = 63.84, y = 28.47, faction = "B", continent = 619 },
		{ name = "Illidari Perch", npc = "Adept Jena Moonrath", x = 31.81, y = 46.29, faction = "B", continent = 619 },
		{ name = "Illidari Stand", npc = "Izal Whitemoon", x = 44.60, y = 43.85, faction = "B", continent = 619 },
		{ name = "Shackle's Den", npc = "Avaya Farwind", x = 56.19, y = 58.92, faction = "B", continent = 619 },
		{ name = "Wardens' Redoubt", npc = "Trainee Sylwindial", x = 48.19, y = 72.95, faction = "B", continent = 619 },
		{ name = "Watchers' Aerie", npc = "Trainee Starwhisper", x = 51.75, y = 82.11, faction = "B", continent = 619 },
	},
	["azuremyst isle"] = {
		{ name = "Azure Watch", npc = "Zaldaan", x = 49.71, y = 49.10, faction = "A", continent = 12 },
	},
	["badlands"] = {
		{ name = "Dragon's Mouth", npc = "Jake Badlands", x = 21.57, y = 57.80, faction = "A", continent = 13 },
		{ name = "Dustwind Dig", npc = "Nancy Skybrew", x = 48.99, y = 36.20, faction = "A", continent = 13 },
		{ name = "Bloodwatcher Point", npc = "Selara", x = 52.40, y = 50.74, faction = "H", continent = 13 },
		{ name = "New Kargath", npc = "Gorrik", x = 17.18, y = 40.01, faction = "H", continent = 13 },
		{ name = "Fuselight", npc = "Mixi Sweetride", x = 64.33, y = 35.03, faction = "B", continent = 13 },
	},
	["bastion"] = {
		{ name = "Terrace of the Collectors", npc = "Adrina", x = 35.80, y = 21.07, faction = "B", continent = 1550 },
		{ name = "Sagehaven", npc = "Klassia", x = 44.07, y = 32.45, faction = "B", continent = 1550 },
		{ name = "Hero's Rest", npc = "Navarros", x = 51.37, y = 46.80, faction = "B", continent = 1550 },
		{ name = "Aspirant's Rest", npc = "Rheus", x = 48.10, y = 74.25, faction = "B", continent = 1550 },
		{ name = "Hero's Rest", npc = "Eternal Gateway", x = 51.75, y = 46.81, faction = "B", continent = 1550 },
		{ name = "Aspirant's Rest", npc = "Eternal Gateway", x = 48.33, y = 72.85, faction = "B", continent = 1550 },
		{ name = "Xandria's Vigil", npc = "Eternal Gateway", x = 40.71, y = 55.21, faction = "B", continent = 1550 },
		{ name = "Sagehaven", npc = "Eternal Gateway", x = 44.16, y = 33.02, faction = "B", continent = 1550 },
		{ name = "Temple of Purity", npc = "Eternal Gateway", x = 59.42, y = 77.12, faction = "B", continent = 1550 },
		{ name = "Seat of Eternal Hymns", npc = "Eternal Gateway", x = 58.37, y = 30.97, faction = "B", continent = 1550 },
		{ name = "Temple of Humility", npc = "Eternal Gateway", x = 66.59, y = 47.90, faction = "B", continent = 1550 },
		{ name = "Terrace of the Collectors", npc = "Eternal Gateway", x = 35.40, y = 21.93, faction = "B", continent = 1550 },
	},
	["blade's edge mountains"] = {
		{ name = "Sylvanaar", npc = "Amerun Leafshade", x = 37.82, y = 61.39, faction = "A", continent = 101 },
		{ name = "Toshley's Station", npc = "Rip Pedalslam", x = 61.15, y = 70.44, faction = "A", continent = 101 },
		{ name = "Thunderlord Stronghold", npc = "Unoke Tenderhoof", x = 52.05, y = 54.13, faction = "H", continent = 101 },
		{ name = "Mok'Nathal Village", npc = "Sky-Master Maxxor", x = 76.37, y = 65.93, faction = "H", continent = 101 },
		{ name = "Evergrove", npc = "Fhyn Leafshadow", x = 61.68, y = 39.61, faction = "B", continent = 101 },
		{ name = "Skyguard Outpost", npc = "Skyguard Handler Irena", x = 28.28, y = 52.10, faction = "B", continent = 101 },
	},
	["blasted lands"] = {
		{ name = "Nethergarde Keep", npc = "Alexandra Constantine", x = 61.25, y = 21.58, faction = "A", continent = 13 },
		{ name = "Surwich", npc = "Graham McAllister", x = 47.13, y = 89.36, faction = "A", continent = 13 },
		{ name = "Shattered Beachhead", npc = "Araazi", x = 67.64, y = 27.97, faction = "A", continent = 13 },
		{ name = "Sunveil Excursion", npc = "Salena", x = 50.92, y = 72.88, faction = "H", continent = 13 },
		{ name = "Dreadmaul Hold", npc = "Preda", x = 43.71, y = 14.25, faction = "H", continent = 13 },
		{ name = "Shattered Landing", npc = "Ameri Windblade", x = 72.95, y = 48.63, faction = "H", continent = 13 },
	},
	["bloodmyst isle"] = {
		{ name = "Blood Watch", npc = "Laando", x = 57.68, y = 53.88, faction = "A", continent = 12 },
	},
	["boralus"] = {
		{ name = "Tradewinds Market", npc = "Joan Weber", x = 66.97, y = 15.01, faction = "A", continent = 876 },
		{ name = "Proudmoore Keep", npc = "Jessica Clarke", x = 47.76, y = 65.44, faction = "A", continent = 876 },
		{ name = "Mariner's Row", npc = "Nicolas Araujo", x = 76.64, y = 72.62, faction = "A", continent = 876 },
		{ name = "Tradewinds Market Harbor", npc = "Will Melborne", x = 74.17, y = 24.78, faction = "A", continent = 876 },
	},
	["borean tundra"] = {
		{ name = "Fizzcrank Airstrip", npc = "Kara Thricestar", x = 56.57, y = 20.06, faction = "A", continent = 113 },
		{ name = "Valiance Keep", npc = "Tomas Riverwell", x = 58.96, y = 68.29, faction = "A", continent = 113 },
		{ name = "Warsong Hold", npc = "Turida Coldwind", x = 40.36, y = 51.40, faction = "H", continent = 113 },
		{ name = "Bor'gorok Outpost", npc = "Kimbiza", x = 49.65, y = 11.05, faction = "H", continent = 113 },
		{ name = "Taunka'le Village", npc = "Omu Spiritbreeze", x = 77.76, y = 37.77, faction = "H", continent = 113 },
		{ name = "Transitus Shield", npc = "Warmage Adami", x = 33.13, y = 34.44, faction = "B", continent = 113 },
		{ name = "Amber Ledge", npc = "Surristrasz", x = 45.32, y = 34.49, faction = "B", continent = 113 },
		{ name = "Unu'pe", npc = "Bilko Driftspark", x = 78.54, y = 51.53, faction = "B", continent = 113 },
	},
	["broken shore"] = {
		{ name = "Vengeance Point", npc = "Izal Whitemoon", x = 49.67, y = 21.02, faction = "B", continent = 619 },
		{ name = "Aalgen Point", npc = "Heidirk the Scalekeeper", x = 70.76, y = 47.62, faction = "B", continent = 619 },
		{ name = "Deliverance Point", npc = "Illidari Calia", x = 45.16, y = 64.12, faction = "B", continent = 619 },
		{ name = "Acherus: The Ebon Hold, Broken Shore", npc = "Grimwing", x = 25.51, y = 28.79, faction = "B", continent = 619 },
	},
	["burning steppes"] = {
		{ name = "Morgan's Vigil", npc = "Borgus Stoutarm", x = 72.09, y = 65.70, faction = "A", continent = 13 },
		{ name = "Flame Crest", npc = "Vahgruk", x = 54.17, y = 24.23, faction = "H", continent = 13 },
		{ name = "Chiselgrip", npc = "Grimly Singefeather", x = 46.15, y = 41.79, faction = "B", continent = 13 },
		{ name = "Flamestar Post", npc = "Hans Oreflight", x = 17.79, y = 52.75, faction = "B", continent = 13 },
	},
	["crystalsong forest"] = {
		{ name = "Windrunner's Overlook", npc = "Galendror Whitewing", x = 72.17, y = 80.97, faction = "A", continent = 113 },
		{ name = "Sunreaver's Command", npc = "Skymaster Baeric", x = 78.54, y = 50.41, faction = "H", continent = 113 },
	},
	["dalaran"] = {
		{ name = "Dalaran", npc = "Aludane Whitecloud", x = 72.18, y = 45.77, faction = "B", continent = 113 },
	},
	["dalaran l"] = {
		{ name = "Dalaran", npc = "Aludane Whitecloud", x = 69.83, y = 51.11, faction = "B", continent = 619 },
	},
	["darkshore"] = {
		{ name = "Grove of the Ancients", npc = "Delanea", x = 44.41, y = 75.47, faction = "A", continent = 12 },
		{ name = "Lor'danel", npc = "Teldira Moonfeather", x = 51.72, y = 17.65, faction = "A", continent = 12 },
		{ name = "Lor'danel", npc = "Nightsaber Rider", x = 52.22, y = 22.27, faction = "A", continent = 12 },
		{ name = "Lor'danel", npc = "Nightsaber Rider", x = 51.03, y = 22.75, faction = "A", continent = 12 },
		{ name = "Ruins of Mathystra", npc = "Nightsaber Rider", x = 58.57, y = 19.99, faction = "A", continent = 12 },
		{ name = "Shatterspear Vale", npc = "Nightsaber Rider", x = 69.11, y = 18.87, faction = "A", continent = 12 },
		{ name = "Bashal'Aran", npc = "Nightsaber Rider", x = 46.85, y = 33.18, faction = "A", continent = 12 },
	},
	["darnassus"] = {
		{ name = "Darnassus", npc = "Leora", x = 36.61, y = 47.83, faction = "A", continent = 12 },
	},
	["dazar'alor"] = {
		{ name = "The Great Seal", npc = "Paku'ai Rokota", x = 51.91, y = 41.21, faction = "H", continent = 875 },
		{ name = "Port of Zandalar", npc = "Ripa the Wind Ripper", x = 52.09, y = 90.11, faction = "H", continent = 875 },
		{ name = "The Sliver", npc = "Zena the Feeder", x = 53.15, y = 19.35, faction = "H", continent = 875 },
	},
	["desolace"] = {
		{ name = "Nijel's Point", npc = "Baritanas Skyriver", x = 64.66, y = 10.54, faction = "A", continent = 12 },
		{ name = "Thargad's Camp", npc = "Moira Steelwing", x = 36.76, y = 71.68, faction = "A", continent = 12 },
		{ name = "Furien's Post", npc = "Narimar", x = 44.28, y = 29.68, faction = "H", continent = 12 },
		{ name = "Shadowprey Village", npc = "Thalon", x = 21.60, y = 74.13, faction = "H", continent = 12 },
		{ name = "Ethel Rethor", npc = "Korrah's Hippogryph", x = 39.07, y = 26.93, faction = "B", continent = 12 },
		{ name = "Karnum's Glade", npc = "Lastrea Greengale", x = 57.72, y = 49.75, faction = "B", continent = 12 },
		{ name = "Thunk's Abode", npc = "Thunk's Wyvern", x = 70.67, y = 32.89, faction = "B", continent = 12 },
	},
	["dornogal"] = {
		{ name = "Dornogal", npc = "Breem", x = 44.67, y = 51.16, faction = "B", continent = 2274 },
	},
	["dragonblight"] = {
		{ name = "Stars' Rest", npc = "Palena Silvercloud", x = 29.18, y = 55.32, faction = "A", continent = 113 },
		{ name = "Fordragon Hold", npc = "Derek Rammel", x = 39.52, y = 25.91, faction = "A", continent = 113 },
		{ name = "Wintergarde Keep", npc = "Rodney Wells", x = 77.00, y = 49.79, faction = "A", continent = 113 },
		{ name = "Agmar's Hammer", npc = "Narzun Skybreaker", x = 37.51, y = 45.76, faction = "H", continent = 113 },
		{ name = "Kor'kron Vanguard", npc = "Numo Spiritbreeze", x = 43.85, y = 16.94, faction = "H", continent = 113 },
		{ name = "Venomspite", npc = "Junter Weiss", x = 76.48, y = 62.21, faction = "H", continent = 113 },
		{ name = "Wyrmrest Temple", npc = "Nethestrasz", x = 60.32, y = 51.55, faction = "B", continent = 113 },
		{ name = "Moa'ki", npc = "Cid Flounderfix", x = 48.51, y = 74.39, faction = "B", continent = 113 },
	},
	["dread wastes"] = {
		{ name = "The Sunset Brewgarden", npc = "Jin the Flying Keg", x = 50.20, y = 12.24, faction = "B", continent = 424 },
		{ name = "Klaxxi'vess", npc = "Kik'tik", x = 55.83, y = 34.88, faction = "B", continent = 424 },
		{ name = "Soggy's Gamble", npc = "Min the Breeze Rider", x = 56.10, y = 70.18, faction = "B", continent = 424 },
		{ name = "The Briny Muck", npc = "Infiltrator Ik'thal", x = 42.53, y = 55.75, faction = "B", continent = 424 },
	},
	["drustvar"] = {
		{ name = "Hangman's Point", npc = "Aaron Ridgeley", x = 71.06, y = 40.88, faction = "A", continent = 876 },
		{ name = "Fletcher's Hollow", npc = "Bridget Bran", x = 70.21, y = 60.45, faction = "A", continent = 876 },
		{ name = "Falconhurst", npc = "Viviana Swailes", x = 26.98, y = 72.38, faction = "A", continent = 876 },
		{ name = "Arom's Stand", npc = "Jess Albury", x = 38.14, y = 52.53, faction = "A", continent = 876 },
		{ name = "Watchman's Rise", npc = "Ensign Wallace", x = 31.87, y = 30.45, faction = "A", continent = 876 },
		{ name = "Fallhaven", npc = "Clarence Page", x = 55.13, y = 34.70, faction = "A", continent = 876 },
		{ name = "Barbthorn Ridge", npc = "Anna Ridgeley", x = 62.61, y = 23.99, faction = "A", continent = 876 },
		{ name = "Krazzlefrazz Outpost", npc = "Rixi Rocketboom", x = 37.37, y = 24.04, faction = "H", continent = 876 },
		{ name = "Swiftwind Post", npc = "Windtamer Loka", x = 66.46, y = 59.32, faction = "H", continent = 876 },
		{ name = "Mudfisher Cove", npc = "Drasha Windspear", x = 62.03, y = 16.88, faction = "H", continent = 876 },
		{ name = "Anyport", npc = "Tan Lotuswind", x = 19.14, y = 43.31, faction = "B", continent = 876 },
		{ name = "Whitegrove Chapel", npc = "Bertram", x = 25.74, y = 16.56, faction = "B", continent = 876 },
		{ name = "Fletcher's Hollow", npc = "Ian Glassel", x = 69.38, y = 57.29, faction = "A", continent = 876 },
		{ name = "Fallhaven", npc = "Helen Waterview", x = 61.70, y = 36.56, faction = "A", continent = 876 },
	},
	["dun morogh"] = {
		{ name = "Gol'Bolar Quarry", npc = "Dominic Galebeard", x = 75.87, y = 54.44, faction = "A", continent = 13 },
		{ name = "Kharanos", npc = "Brolan Galebeard", x = 53.80, y = 52.76, faction = "A", continent = 13 },
	},
	["durotar"] = {
		{ name = "Razor Hill", npc = "Burok", x = 53.09, y = 43.58, faction = "H", continent = 12 },
		{ name = "Sen'jin Village", npc = "Handler Marnlek", x = 55.38, y = 73.31, faction = "H", continent = 12 },
	},
	["duskwood"] = {
		{ name = "Darkshire", npc = "Felicia Maline", x = 77.48, y = 44.28, faction = "A", continent = 13 },
		{ name = "Raven Hill", npc = "John Shelby", x = 21.08, y = 56.44, faction = "A", continent = 13 },
	},
	["dustwallow marsh"] = {
		{ name = "Theramore", npc = "Baldruc", x = 67.48, y = 51.30, faction = "A", continent = 12 },
		{ name = "Brackenwall Village", npc = "Shardi", x = 35.57, y = 31.88, faction = "H", continent = 12 },
		{ name = "Mudsprocket", npc = "Dyslix Silvergrub", x = 42.82, y = 72.43, faction = "B", continent = 12 },
	},
	["eastern plaguelands"] = {
		{ name = "Light's Hope Chapel", npc = "Khaelyn Steelwing", x = 75.85, y = 53.41, faction = "A", continent = 13 },
		{ name = "Acherus: The Ebon Hold", npc = "Grimwing", x = 83.89, y = 50.43, faction = "A", continent = 13 },
		{ name = "Light's Hope Chapel", npc = "Georgia", x = 75.81, y = 53.29, faction = "H", continent = 13 },
		{ name = "Acherus: The Ebon Hold", npc = "Grimwing", x = 83.89, y = 50.43, faction = "H", continent = 13 },
		{ name = "Eastwall Tower", npc = "Richard Trueflight", x = 61.64, y = 43.84, faction = "B", continent = 13 },
		{ name = "Northpass Tower", npc = "Grayson Ironwing", x = 51.35, y = 21.31, faction = "B", continent = 13 },
		{ name = "Light's Shield Tower", npc = "Devon Manning", x = 52.77, y = 53.57, faction = "B", continent = 13 },
		{ name = "Crown Guard Tower", npc = "Janice Myers", x = 34.90, y = 67.89, faction = "B", continent = 13 },
		{ name = "Plaguewood Tower", npc = "William Kielar Jr.", x = 18.46, y = 27.37, faction = "B", continent = 13 },
		{ name = "Thondroril River", npc = "Frax Bucketdrop", x = 10.09, y = 65.66, faction = "B", continent = 13 },
	},
	["elwynn forest"] = {
		{ name = "Goldshire", npc = "Bartlett the Brave", x = 41.71, y = 64.64, faction = "A", continent = 13 },
		{ name = "Eastvale Logging Camp", npc = "Goss the Swift", x = 81.83, y = 66.56, faction = "A", continent = 13 },
	},
	["elysian hold"] = {
		{ name = "Elysian Hold", npc = "Cassius", x = 50.94, y = 49.03, faction = "B", continent = 1550 },
		{ name = "Elysian Hold", npc = "Eternal Gateway", x = 48.67, y = 61.68, faction = "B", continent = 1550 },
	},
	["eredath"] = {
		{ name = "Vindicaar, Eredath", npc = "", x = 48.98, y = 23.13, faction = "B", continent = 994 },
		{ name = "Triumvirate's End, Eredath", npc = "", x = 52.86, y = 75.46, faction = "B", continent = 994 },
		{ name = "Conservatory of the Arcane, Eredath", npc = "", x = 62.98, y = 39.49, faction = "B", continent = 994 },
		{ name = "Prophet's Reflection, Eredath", npc = "", x = 43.87, y = 14.53, faction = "B", continent = 994 },
		{ name = "Shadowguard Incursion, Eredath", npc = "", x = 30.16, y = 49.56, faction = "B", continent = 994 },
		{ name = "City Center, Eredath", npc = "", x = 47.03, y = 55.50, faction = "B", continent = 994 },
	},
	["eversong woods"] = {
		{ name = "Fairbreeze Village", npc = "Skymaster Brightdawn", x = 43.94, y = 69.98, faction = "H", continent = 13 },
		{ name = "Silvermoon City", npc = "Skymistress Gloaming", x = 54.37, y = 50.73, faction = "H", continent = 13 },
		{ name = "Falconwing Square", npc = "Skymaster Skyles", x = 46.25, y = 46.79, faction = "H", continent = 13 },
	},
	["eversong woods m"] = {
		{ name = "Silverglade Refuge", npc = "Galendror Whitewing", x = 31.01, y = 90.07, faction = "A", continent = 13 },
		{ name = "Fairbreeze Village", npc = "Vael'thas Dawnsoar", x = 44.70, y = 44.98, faction = "B", continent = 13 },
		{ name = "Tranquillien", npc = "Skymaster Sunwing", x = 47.80, y = 67.13, faction = "B", continent = 13 },
	},
	["eye of azshara map"] = {
		{ name = "Eye of Azshara", npc = "Razen Swingblade", x = 38.28, y = 46.07, faction = "B", continent = 619 },
	},
	["felwood"] = {
		{ name = "Talonbranch Glade", npc = "Mishellena", x = 60.52, y = 25.29, faction = "A", continent = 12 },
		{ name = "Irontree Clearing", npc = "Dirzak Pryocrank", x = 56.36, y = 8.64, faction = "H", continent = 12 },
		{ name = "Emerald Sanctuary", npc = "Gorrim", x = 51.53, y = 80.87, faction = "B", continent = 12 },
		{ name = "Whisperwind Grove", npc = "Hanah Southsong", x = 43.59, y = 28.70, faction = "B", continent = 12 },
		{ name = "Wildheart Point", npc = "Chyella Hushglade", x = 44.29, y = 61.87, faction = "B", continent = 12 },
	},
	["feralas"] = {
		{ name = "Dreamer's Rest", npc = "Selor", x = 50.21, y = 16.72, faction = "A", continent = 12 },
		{ name = "Feathermoon", npc = "Irela Moonfeather", x = 46.77, y = 45.35, faction = "A", continent = 12 },
		{ name = "Shadebough", npc = "Seyala Nightwisp", x = 77.31, y = 56.79, faction = "A", continent = 12 },
		{ name = "Tower of Estulan", npc = " Aryenda", x = 57.08, y = 53.95, faction = "A", continent = 12 },
		{ name = "Camp Ataya", npc = "Tono", x = 41.54, y = 15.46, faction = "H", continent = 12 },
		{ name = "Camp Mojache", npc = "Shyn", x = 75.45, y = 44.36, faction = "H", continent = 12 },
		{ name = "Stonemaul Hold", npc = "Mergek", x = 51.00, y = 48.42, faction = "H", continent = 12 },
	},
	["founder's point"] = {
		{ name = "Entrance Portal", npc = "Jeff", x = 56.62, y = 27.60, faction = "A", continent = 13 },
		{ name = "Town Center", npc = "Billson", x = 51.27, y = 39.58, faction = "A", continent = 13 },
		{ name = "Small Aerie", npc = "Norbert", x = 43.31, y = 44.88, faction = "A", continent = 13 },
		{ name = "Mear's Farm", npc = "Eibhlin", x = 34.64, y = 34.24, faction = "A", continent = 13 },
		{ name = "The Outer Banks", npc = "Niels", x = 32.40, y = 45.88, faction = "A", continent = 13 },
		{ name = "Gilded Oaks", npc = "Landan", x = 38.05, y = 62.80, faction = "A", continent = 13 },
		{ name = "Brumewood Hollow", npc = "Lensholvada", x = 56.32, y = 58.03, faction = "A", continent = 13 },
		{ name = "Stoneveil Ridge", npc = "Arneu", x = 63.67, y = 41.44, faction = "A", continent = 13 },
	},
	["frostfire ridge"] = {
		{ name = "Iron Siegeworks", npc = "Rangari Veera", x = 87.42, y = 62.60, faction = "A", continent = 572 },
		{ name = "Stonefang Outpost", npc = "Skyhunter Donmor'gan", x = 40.11, y = 51.84, faction = "H", continent = 572 },
		{ name = "Wor'gol", npc = "Pul Windcarver", x = 21.57, y = 56.15, faction = "H", continent = 572 },
		{ name = "Throm'Var", npc = "Jonnock Hewndawn", x = 31.83, y = 9.56, faction = "H", continent = 572 },
		{ name = "Darkspear's Edge", npc = "Ja'kana", x = 51.70, y = 41.12, faction = "H", continent = 572 },
		{ name = "Wolf's Stand", npc = "Windhunter", x = 73.63, y = 60.03, faction = "H", continent = 572 },
		{ name = "Thunder Pass", npc = "Bile Warneck", x = 83.62, y = 60.88, faction = "H", continent = 572 },
		{ name = "Bladespire Citadel", npc = "Roark the Airwolf", x = 19.95, y = 51.78, faction = "H", continent = 572 },
		{ name = "Bloodmaul Slag Mines", npc = "Brenna Skymoor", x = 51.45, y = 21.45, faction = "B", continent = 572 },
	},
	["frostwall"] = {
		{ name = "Frostwall", npc = "Bron Skyhorn", x = 45.79, y = 50.92, faction = "H", continent = 572 },
	},
	["ghostlands"] = {
		{ name = "Tranquillien", npc = "Skymaster Sunwing", x = 45.42, y = 30.52, faction = "H", continent = 13 },
		{ name = "Zul'Aman", npc = "Kiz Coilspanner", x = 74.76, y = 67.15, faction = "B", continent = 13 },
	},
	["gorgrond"] = {
		{ name = "Deeproot", npc = "Rangari Nogo", x = 46.47, y = 76.60, faction = "A", continent = 572 },
		{ name = "Highpass", npc = "Rangari Rajess", x = 52.83, y = 59.33, faction = "A", continent = 572 },
		{ name = "Wildwood Wash", npc = "Rangari Thewe", x = 64.16, y = 57.50, faction = "A", continent = 572 },
		{ name = "Bastion Rise", npc = "Rangari Yaval", x = 46.40, y = 92.41, faction = "A", continent = 572 },
		{ name = "Evermorn Springs", npc = "Chucklespine", x = 41.31, y = 87.17, faction = "H", continent = 572 },
		{ name = "Bastion Rise", npc = "Windscreamer", x = 47.43, y = 90.79, faction = "H", continent = 572 },
		{ name = "Beastwatch", npc = "Grinslicer", x = 45.98, y = 69.22, faction = "H", continent = 572 },
		{ name = "Breaker's Crown", npc = "Nisha", x = 45.87, y = 54.94, faction = "B", continent = 572 },
		{ name = "Everbloom Wilds", npc = "Arcanist Windlebop", x = 57.01, y = 45.88, faction = "B", continent = 572 },
		{ name = "Skysea Ridge", npc = "Faronn Dustwalker", x = 39.55, y = 36.58, faction = "B", continent = 572 },
		{ name = "Iron Docks", npc = "Nisha", x = 43.04, y = 20.21, faction = "B", continent = 572 },
		{ name = "Everbloom Overlook", npc = "Researcher Sarix", x = 68.72, y = 28.75, faction = "B", continent = 572 },
	},
	["gravid repose"] = {
		{ name = "Gravid Repose Locus", npc = "Locus Shift", x = 59.35, y = 41.51, faction = "B", continent = 1970 },
		{ name = "Interior Locus", npc = "Locus Shift", x = 40.33, y = 34.34, faction = "B", continent = 1970 },
		{ name = "Arcae Locus", npc = "Locus Shift", x = 40.33, y = 34.34, faction = "B", continent = 1970 },
		{ name = "Rondure Alcove", npc = "Locus Shift", x = 43.00, y = 39.89, faction = "B", continent = 1970 },
		{ name = "Dormant Alcove", npc = "Locus Shift", x = 40.33, y = 34.34, faction = "B", continent = 1970 },
		{ name = "Fulgor Alcove", npc = "Locus Shift", x = 40.33, y = 34.34, faction = "B", continent = 1970 },
		{ name = "Repertory Alcove", npc = "Locus Shift", x = 40.33, y = 34.34, faction = "B", continent = 1970 },
		{ name = "Camber Alcove", npc = "Locus Shift", x = 40.33, y = 34.34, faction = "B", continent = 1970 },
	},
	["grizzly hills"] = {
		{ name = "Amberpine Lodge", npc = "Vana Grey", x = 31.31, y = 59.11, faction = "A", continent = 113 },
		{ name = "Westfall Brigade", npc = "Samuel Clearbook", x = 59.89, y = 26.68, faction = "A", continent = 113 },
		{ name = "Conquest Hold", npc = "Kragh", x = 21.99, y = 64.43, faction = "H", continent = 113 },
		{ name = "Camp Oneqwah", npc = "Makki Wintergale", x = 64.96, y = 46.93, faction = "H", continent = 113 },
	},
	["hallowfall"] = {
		{ name = "The Aegis Wall", npc = "Vellas Tearen", x = 71.36, y = 56.50, faction = "B", continent = 2274 },
		{ name = "Lightspark", npc = "Gear Flamepierce", x = 52.86, y = 61.33, faction = "B", continent = 2274 },
		{ name = "Light's Redoubt", npc = "'Red' Fearon", x = 40.45, y = 71.31, faction = "B", continent = 2274 },
		{ name = "Mereldar", npc = "Anje Noon", x = 41.57, y = 52.59, faction = "B", continent = 2274 },
		{ name = "Lorel's Crossing", npc = "Bastian Wynfall", x = 48.38, y = 40.71, faction = "B", continent = 2274 },
		{ name = "Priory of the Sacred Flame", npc = "Tristan Lyte", x = 41.14, y = 33.66, faction = "B", continent = 2274 },
		{ name = "Hillhelm Family Farm", npc = "Rubaen Hillhelm", x = 61.34, y = 30.99, faction = "B", continent = 2274 },
		{ name = "Dunelle's Kindness", npc = "Auro Flitter", x = 67.48, y = 44.62, faction = "B", continent = 2274 },
	},
	["harandar"] = {
		{ name = "Har'athir", npc = "Nae'thali", x = 69.36, y = 52.60, faction = "B", continent = 2413 },
		{ name = "Har'mara", npc = "Sa'neya", x = 35.53, y = 23.81, faction = "B", continent = 2413 },
		{ name = "The Den", npc = "Doecha", x = 54.10, y = 53.23, faction = "B", continent = 2413 },
		{ name = "Har'alnor", npc = "Ka'mura", x = 31.73, y = 67.43, faction = "B", continent = 2413 },
		{ name = "Har'kuai", npc = "Lo'miko", x = 64.59, y = 23.15, faction = "B", continent = 2413 },
	},
	["hellfire peninsula"] = {
		{ name = "Honor Hold", npc = "Krill Bitterhue", x = 54.68, y = 62.35, faction = "A", continent = 101 },
		{ name = "Shatter Point", npc = "Runetog Wildhammer", x = 78.42, y = 34.90, faction = "A", continent = 101 },
		{ name = "Temple of Telhamat", npc = "Kuma", x = 25.19, y = 37.23, faction = "A", continent = 101 },
		{ name = "Hellfire Peninsula, The Dark Portal", npc = "Amish Wildhammer", x = 87.36, y = 52.42, faction = "A", continent = 101 },
		{ name = "Falcon Watch", npc = "Innalia", x = 27.79, y = 59.98, faction = "H", continent = 101 },
		{ name = "Spinebreaker Ridge", npc = "Amilya Airheart", x = 61.65, y = 81.19, faction = "H", continent = 101 },
		{ name = "Hellfire Peninsula, The Dark Portal", npc = "Vlagga Freyfeather", x = 87.35, y = 48.14, faction = "H", continent = 101 },
		{ name = "Thrallmar", npc = "Barley", x = 56.29, y = 36.25, faction = "H", continent = 101 },
	},
	["highmountain"] = {
		{ name = "Felbane Camp", npc = "Kimben Wingheart", x = 29.93, y = 39.32, faction = "B", continent = 619 },
		{ name = "Ironhorn Enclave", npc = "Poca Firemantle", x = 56.82, y = 83.85, faction = "B", continent = 619 },
		{ name = "Nesingwary", npc = "Tamara Sigmund", x = 40.23, y = 52.70, faction = "B", continent = 619 },
		{ name = "Obsidian Overlook", npc = "Chofa Nighthoof", x = 47.26, y = 84.64, faction = "B", continent = 619 },
		{ name = "Prepfoot", npc = "Brun Prepfoot", x = 57.98, y = 28.62, faction = "B", continent = 619 },
		{ name = "Shipwreck Cove", npc = "Steven Nelson", x = 41.90, y = 10.42, faction = "B", continent = 619 },
		{ name = "Skyhorn", npc = "Farah Skybeak", x = 52.60, y = 45.32, faction = "B", continent = 619 },
		{ name = "Stonehoof Watch", npc = "Lassa Skymane", x = 59.23, y = 65.05, faction = "B", continent = 619 },
		{ name = "Sylvan Falls", npc = "Roren Longshadow", x = 35.86, y = 65.92, faction = "B", continent = 619 },
		{ name = "The Witchwood", npc = "Rafat Smokehoof", x = 38.35, y = 39.29, faction = "B", continent = 619 },
	},
	["hillsbrad foothills"] = {
		{ name = "Eastpoint Tower", npc = "Darren Longfellow", x = 59.61, y = 63.25, faction = "H", continent = 13 },
		{ name = "Ruins of Southshore", npc = "Darla Harris", x = 49.02, y = 66.21, faction = "H", continent = 13 },
		{ name = "Southpoint Gate", npc = "Pamela Stutzka", x = 29.14, y = 64.41, faction = "H", continent = 13 },
		{ name = "Strahnbrad", npc = "Phillip Harding", x = 58.23, y = 26.48, faction = "H", continent = 13 },
		{ name = "Tarren Mill", npc = "Zarise", x = 56.06, y = 46.08, faction = "H", continent = 13 },
	},
	["howling fjord"] = {
		{ name = "Fort Wildervar", npc = "James Ormsby", x = 60.06, y = 16.11, faction = "A", continent = 113 },
		{ name = "Valgarde Port", npc = "Pricilla Winterwind", x = 59.79, y = 63.24, faction = "A", continent = 113 },
		{ name = "Westguard Keep", npc = "Greer Orehammer", x = 31.26, y = 43.98, faction = "A", continent = 113 },
		{ name = "Camp Winterhoof", npc = "Celea Frozenmane", x = 49.56, y = 11.59, faction = "H", continent = 113 },
		{ name = "Vengeance Landing", npc = "Adeline Chambers", x = 79.04, y = 29.71, faction = "H", continent = 113 },
		{ name = "New Agamand", npc = "Tobias Sarkhoff", x = 52.01, y = 67.38, faction = "H", continent = 113 },
		{ name = "Apothecary Camp", npc = "Lilleth Radescu", x = 25.98, y = 25.07, faction = "H", continent = 113 },
		{ name = "Kamagua", npc = "Kip Trawlskip", x = 24.66, y = 57.77, faction = "B", continent = 113 },
	},
	["icecrown"] = {
		{ name = "The Shadow Vault", npc = "Morlia Doomwing", x = 43.74, y = 24.38, faction = "A", continent = 113 },
		{ name = "The Shadow Vault", npc = "Morlia Doomwing", x = 43.74, y = 24.38, faction = "H", continent = 113 },
		{ name = "Argent Tournament Grounds", npc = "Helidan Lightwing", x = 72.59, y = 22.61, faction = "B", continent = 113 },
		{ name = "Death's Rise", npc = "Dreadwind", x = 19.34, y = 47.78, faction = "B", continent = 113 },
		{ name = "Crusaders' Pinnacle", npc = "Penumbrius", x = 79.41, y = 72.36, faction = "B", continent = 113 },
		{ name = "The Argent Vanguard", npc = "Aedan Moran", x = 87.80, y = 78.07, faction = "B", continent = 113 },
	},
	["ironforge"] = {
		{ name = "Ironforge", npc = "Gryth Thurden", x = 55.51, y = 47.74, faction = "A", continent = 13 },
	},
	["isle of dorn"] = {
		{ name = "Freywold Village", npc = "Iridi", x = 41.04, y = 72.93, faction = "B", continent = 2274 },
		{ name = "Durgaz Cabin", npc = "Drelda", x = 67.48, y = 43.31, faction = "B", continent = 2274 },
		{ name = "Rambleshire", npc = "Tordrin", x = 59.16, y = 28.58, faction = "B", continent = 2274 },
		{ name = "Tranquil Strand", npc = "Flying Carpet", x = 29.74, y = 58.34, faction = "B", continent = 2274 },
	},
	["isle of giants"] = {
		{ name = "Beeble's Wreck", npc = "Beeble Sockwrench", x = 41.75, y = 79.31, faction = "A", continent = 424 },
		{ name = "Bozzle's Wreck", npc = "Bozzle Blastinfuse", x = 52.02, y = 75.50, faction = "H", continent = 424 },
	},
	["isle of quel danas m"] = {
		{ name = "Terrace of the Sun", npc = "Skymistress Gloaming", x = 57.55, y = 33.85, faction = "B", continent = 13 },
	},
	["isle of quel'danas"] = {
		{ name = "Shattered Sun Staging Area", npc = "Ohura", x = 48.36, y = 25.07, faction = "B", continent = 13 },
	},
	["k'aresh"] = {
		{ name = "Hosaas' Rest", npc = "Om'Dodaf", x = 54.21, y = 62.83, faction = "B", continent = 2274 },
		{ name = "Eco-Dome: Rhovan", npc = "Om'Toya", x = 70.19, y = 60.91, faction = "B", continent = 2274 },
		{ name = "The Oasis", npc = "Om'Khell", x = 76.66, y = 34.94, faction = "B", continent = 2274 },
		{ name = "Shan'dorah", npc = "Sellyna", x = 60.61, y = 29.20, faction = "B", continent = 2274 },
		{ name = "Overlook Zo'Shuul", npc = "Om'Qaxxi", x = 47.81, y = 37.26, faction = "B", continent = 2274 },
		{ name = "Shadow Point", npc = "Lossain", x = 42.24, y = 22.71, faction = "B", continent = 2274 },
		{ name = "Hosaas' Rest", npc = "Phase Conduit", x = 53.85, y = 63.60, faction = "B", continent = 2274 },
		{ name = "Ruins of Yaathron", npc = "Phase Conduit", x = 51.38, y = 67.14, faction = "B", continent = 2274 },
		{ name = "The Oasis", npc = "Phase Conduit", x = 75.88, y = 33.10, faction = "B", continent = 2274 },
		{ name = "Shan'dorah", npc = "Phase Conduit", x = 60.21, y = 29.05, faction = "B", continent = 2274 },
		{ name = "Overlook Zo'Shuul", npc = "Phase Conduit", x = 50.41, y = 36.40, faction = "B", continent = 2274 },
		{ name = "Shadow Point", npc = "Phase Conduit", x = 45.21, y = 23.91, faction = "B", continent = 2274 },
		{ name = "Naakroa", npc = "Phase Conduit", x = 58.90, y = 57.89, faction = "B", continent = 2274 },
		{ name = "Serrated Peaks", npc = "Phase Conduit", x = 51.21, y = 48.57, faction = "B", continent = 2274 },
		{ name = "Lunnall River", npc = "Phase Conduit", x = 65.44, y = 47.98, faction = "B", continent = 2274 },
		{ name = "North Sufaad", npc = "Phase Conduit", x = 77.17, y = 48.93, faction = "B", continent = 2274 },
		{ name = "Fracture of Laacuna", npc = "Phase Conduit", x = 56.20, y = 21.51, faction = "B", continent = 2274 },
		{ name = "Untethered Space", npc = "Phase Conduit", x = 53.92, y = 26.75, faction = "B", continent = 2274 },
	},
	["kelp'thar forest"] = {
		{ name = "Sandy Beach", npc = "Swift Seahorse", x = 42.43, y = 66.13, faction = "A", continent = 13 },
		{ name = "Sandy Beach", npc = "Swift Seahorse", x = 49.30, y = 87.89, faction = "H", continent = 13 },
		{ name = "Smuggler's Scar", npc = "Swift Seahorse", x = 56.12, y = 31.13, faction = "B", continent = 13 },
	},
	["korthia"] = {
		{ name = "Keeper's Respite", npc = "Animaflow Teleporter", x = 64.97, y = 23.67, faction = "B", continent = 1550 },
	},
	["krasarang wilds"] = {
		{ name = "Sentinel Basecamp", npc = "Maylen Moonfeather", x = 25.14, y = 33.46, faction = "A", continent = 424 },
		{ name = "Lion's Landing", npc = "Daggin Windbeard", x = 88.33, y = 34.69, faction = "A", continent = 424 },
		{ name = "The Incursion", npc = "Tylen Moonfeather", x = 67.77, y = 32.49, faction = "A", continent = 424 },
		{ name = "Thunder Cleft", npc = "Lira Skysplitter", x = 59.20, y = 24.67, faction = "H", continent = 424 },
		{ name = "Dawnchaser Retreat", npc = "Munch Windhoof", x = 29.00, y = 50.32, faction = "H", continent = 424 },
		{ name = "Domination Point", npc = "Kromthar", x = 9.69, y = 52.51, faction = "H", continent = 424 },
		{ name = "Marista", npc = "Nan-Po", x = 52.48, y = 76.60, faction = "B", continent = 424 },
		{ name = "Cradle of Chi-Ji", npc = "Feather Keeper Li", x = 31.14, y = 63.16, faction = "B", continent = 424 },
		{ name = "Zhu's Watch", npc = "Gee Hung", x = 76.74, y = 8.38, faction = "B", continent = 424 },
	},
	["krokuun"] = {
		{ name = "Vindicaar, Krokuun", npc = "", x = 42.58, y = 22.78, faction = "B", continent = 994 },
		{ name = "Krokul Hovel, Krokuun", npc = "", x = 55.48, y = 67.35, faction = "B", continent = 994 },
		{ name = "Shattered Fields, Krokuun", npc = "", x = 40.30, y = 63.50, faction = "B", continent = 994 },
		{ name = "Destiny Point, Krokuun", npc = "", x = 62.69, y = 49.12, faction = "B", continent = 994 },
	},
	["kun-lai summit"] = {
		{ name = "Westwind Rest", npc = "Tabo the Flyer", x = 53.98, y = 84.27, faction = "A", continent = 424 },
		{ name = "Eastwind Rest", npc = "Soaring Paw", x = 62.43, y = 80.72, faction = "H", continent = 424 },
		{ name = "Serpent's Spine", npc = "Morla Skyblade", x = 35.97, y = 83.71, faction = "H", continent = 424 },
		{ name = "Binan Village", npc = "Jo the Wind Watcher", x = 72.55, y = 94.17, faction = "B", continent = 424 },
		{ name = "Temple of the White Tiger", npc = "Big Greenfeather", x = 66.31, y = 50.67, faction = "B", continent = 424 },
		{ name = "Zouchin Village", npc = "Bo the Wind Claimer", x = 62.42, y = 30.12, faction = "B", continent = 424 },
		{ name = "One Keg", npc = "Little Cleankite", x = 57.73, y = 59.69, faction = "B", continent = 424 },
		{ name = "Kota Basecamp", npc = "Uncle Eastwind", x = 42.81, y = 69.64, faction = "B", continent = 424 },
		{ name = "Shado-Pan Fallback", npc = "Kite Master Ni", x = 43.91, y = 89.54, faction = "B", continent = 424 },
		{ name = "Winter's Blossom", npc = "Kite Master Len", x = 34.54, y = 59.12, faction = "B", continent = 424 },
	},
	["loch modan"] = {
		{ name = "Farstrider Lodge", npc = "Eeryven Grayer", x = 81.88, y = 64.07, faction = "A", continent = 13 },
		{ name = "Thelsamar", npc = "Thorgrum Borrelson", x = 33.94, y = 50.95, faction = "A", continent = 13 },
	},
	["lunarfall"] = {
		{ name = "Lunarfall", npc = "Dungar Longdrink", x = 47.99, y = 49.81, faction = "A", continent = 572 },
	},
	["maldraxxus"] = {
		{ name = "Theater of Pain", npc = "Wing Guard Alamar", x = 49.91, y = 53.40, faction = "B", continent = 1550 },
		{ name = "Plague Watch", npc = "Vradira Livid", x = 58.14, y = 72.45, faction = "B", continent = 1550 },
		{ name = "Renounced Bastille", npc = "Felsen Wingclip", x = 67.93, y = 45.84, faction = "B", continent = 1550 },
		{ name = "Keres' Rest", npc = "Fly-eyed Eliera", x = 53.82, y = 30.69, faction = "B", continent = 1550 },
		{ name = "Spider's Watch", npc = "Flight Master Nudolva", x = 37.51, y = 29.22, faction = "B", continent = 1550 },
		{ name = "The Spearhead", npc = "Wing Guard Aela", x = 39.03, y = 55.24, faction = "B", continent = 1550 },
		{ name = "Bleak Redoubt", npc = "Wing Guard Buurkin", x = 52.47, y = 67.65, faction = "B", continent = 1550 },
	},
	["mechagon island"] = {
		{ name = "Overspark Expedition Camp", npc = "Cog Captain Winklespring", x = 77.83, y = 40.94, faction = "A", continent = 876 },
		{ name = "Prospectus Bay", npc = "Lazz of Leisure", x = 73.48, y = 25.80, faction = "H", continent = 876 },
	},
	["moonglade"] = {
		{ name = "Moonglade", npc = "Sindrayl", x = 48.10, y = 67.34, faction = "A", continent = 12 },
		{ name = "Nighthaven", npc = "Silva Fil'naveth", x = 44.15, y = 45.22, faction = "A", continent = 12 },
		{ name = "Moonglade", npc = "Faustron", x = 32.10, y = 66.61, faction = "H", continent = 12 },
		{ name = "Nighthaven", npc = "Bunthen Plainswind", x = 44.29, y = 45.87, faction = "H", continent = 12 },
	},
	["mount hyjal"] = {
		{ name = "Gates of Sothann", npc = "Althera", x = 71.61, y = 75.34, faction = "B", continent = 12 },
		{ name = "Grove of Aessina", npc = "Elizil Wintermoth", x = 19.59, y = 36.38, faction = "B", continent = 12 },
		{ name = "Nordrassil", npc = "Fayran Elthas", x = 62.13, y = 21.59, faction = "B", continent = 12 },
		{ name = "Sanctuary of Malorne", npc = "Ranela Featherglen", x = 27.75, y = 63.64, faction = "B", continent = 12 },
		{ name = "Shrine of Aviana", npc = "Dinorae Swiftfeather", x = 41.18, y = 42.59, faction = "B", continent = 12 },
	},
	["mulgore"] = {
		{ name = "Bloodhoof Village", npc = "Tak", x = 47.44, y = 58.64, faction = "H", continent = 12 },
	},
	["nagrand"] = {
		{ name = "Telaar", npc = "Furgu", x = 54.17, y = 75.06, faction = "A", continent = 101 },
		{ name = "Garadar", npc = "Gursha", x = 57.19, y = 35.25, faction = "H", continent = 101 },
	},
	["nagrand d"] = {
		{ name = "Telaari Station", npc = "John Shelby", x = 63.64, y = 61.56, faction = "A", continent = 572 },
		{ name = "Yrel's Watch", npc = "Felicia Maline", x = 62.66, y = 40.65, faction = "A", continent = 572 },
		{ name = "Wor'var", npc = "Tal", x = 83.31, y = 44.68, faction = "H", continent = 572 },
		{ name = "Riverside Post", npc = "Omu Spiritbreeze", x = 49.56, y = 48.06, faction = "H", continent = 572 },
		{ name = "The Ring of Trials", npc = "Biggy Warprofits", x = 79.82, y = 49.72, faction = "B", continent = 572 },
		{ name = "Nivek's Overlook", npc = "Nivek Lee", x = 49.38, y = 75.91, faction = "B", continent = 572 },
		{ name = "Joz's Rylaks", npc = "Joz Navarix", x = 62.24, y = 32.90, faction = "B", continent = 572 },
		{ name = "Rilzit's Holdfast", npc = "Rilzit Mugshot", x = 50.75, y = 30.64, faction = "B", continent = 572 },
		{ name = "Throne of the Elements", npc = "Gixmo Moneycash", x = 73.70, y = 26.65, faction = "B", continent = 572 },
	},
	["naigtal"] = {
		{ name = "Umbral Base Camp", npc = "Manaforge Translocator", x = 46.69, y = 82.90, faction = "B", continent = 2405 },
		{ name = "Nexus Port", npc = "Manaforge Translocator", x = 55.02, y = 46.99, faction = "B", continent = 2405 },
		{ name = "Sporeforge", npc = "Manaforge Translocator", x = 77.29, y = 42.92, faction = "B", continent = 2405 },
		{ name = "Extraction Coast", npc = "Manaforge Translocator", x = 32.27, y = 46.01, faction = "B", continent = 2405 },
	},
	["nazjatar"] = {
		{ name = "Mezzamere", npc = "Ray Tamer Enaka", x = 39.92, y = 54.12, faction = "A", continent = 1355 },
		{ name = "Wreck of the Old Blanchy", npc = "Mandos Fogwing", x = 44.48, y = 85.51, faction = "A", continent = 1355 },
		{ name = "Ashen Strand", npc = "Azuku", x = 31.85, y = 38.09, faction = "A", continent = 1355 },
		{ name = "Utama's Stand", npc = "Hirano", x = 61.68, y = 36.51, faction = "A", continent = 1355 },
		{ name = "Elun'alor Temple", npc = "Orise", x = 73.98, y = 40.03, faction = "A", continent = 1355 },
		{ name = "The Tidal Conflux", npc = "Nobu", x = 49.81, y = 23.62, faction = "A", continent = 1355 },
		{ name = "Newhome", npc = "Iina Bluegill", x = 47.48, y = 63.26, faction = "H", continent = 1355 },
		{ name = "Wreck of the Hungry Riverbeast", npc = "Markona", x = 36.14, y = 82.31, faction = "H", continent = 1355 },
		{ name = "Ashen Strand", npc = "Dren Nautilin", x = 34.45, y = 37.33, faction = "H", continent = 1355 },
		{ name = "Ekka's Hideaway", npc = "Ekka Crimsonscale", x = 63.98, y = 51.81, faction = "H", continent = 1355 },
		{ name = "Zin'Azshari", npc = "Gizzik Kelpears", x = 79.52, y = 37.92, faction = "H", continent = 1355 },
		{ name = "The Tidal Conflux", npc = "Kobo Rayfriend", x = 51.11, y = 23.63, faction = "H", continent = 1355 },
		{ name = "Kelya's Grave", npc = "Kelya Moonfall", x = 74.16, y = 24.92, faction = "B", continent = 1355 },
	},
	["nazmir"] = {
		{ name = "Zo'bal Ruins", npc = "Du'ba", x = 40.17, y = 42.83, faction = "H", continent = 875 },
		{ name = "Gloom Hollow", npc = "Cuja", x = 66.98, y = 43.76, faction = "H", continent = 875 },
		{ name = "Zul'jan", npc = "Zabar", x = 38.85, y = 78.14, faction = "H", continent = 875 },
		{ name = "Forlorn Ruins", npc = "Zibir the Wingmaster", x = 82.15, y = 26.69, faction = "H", continent = 875 },
		{ name = "Redfield's Watch", npc = "Joseph Redfield", x = 50.82, y = 20.77, faction = "A", continent = 875 },
		{ name = "Fort Victory", npc = "Selina Duskraven", x = 62.35, y = 41.38, faction = "A", continent = 875 },
		{ name = "Grimwatt's Crash", npc = "Noella Davenport", x = 34.31, y = 63.21, faction = "A", continent = 875 },
	},
	["nerub'ar"] = {
		{ name = "The Burrows", npc = "Tekazza of the Aimless Few", x = 53.99, y = 44.34, faction = "B", continent = 2274 },
	},
	["netherstorm"] = {
		{ name = "Area 52", npc = "Krexcil", x = 33.74, y = 63.99, faction = "B", continent = 101 },
		{ name = "Cosmowrench", npc = "Harpax", x = 65.20, y = 66.81, faction = "B", continent = 101 },
		{ name = "The Stormspire", npc = "Grennik", x = 45.31, y = 34.87, faction = "B", continent = 101 },
	},
	["northern barrens"] = {
		{ name = "Nozzlepot's Outpost", npc = "Gazrix", x = 62.31, y = 17.12, faction = "H", continent = 12 },
		{ name = "The Crossroads", npc = "Devrak", x = 48.70, y = 58.67, faction = "H", continent = 12 },
		{ name = "The Mor'Shan Ramparts", npc = "Gort Goreflight", x = 41.98, y = 15.87, faction = "H", continent = 12 },
		{ name = "Ratchet", npc = "Bragok", x = 69.12, y = 70.70, faction = "B", continent = 12 },
	},
	["northern stranglethorn"] = {
		{ name = "Fort Livingston", npc = "Robert Rhodes", x = 52.64, y = 66.10, faction = "A", continent = 13 },
		{ name = "Rebel Camp", npc = "James Stillair", x = 47.86, y = 11.85, faction = "A", continent = 13 },
		{ name = "Bambala", npc = "Raskha", x = 62.40, y = 39.24, faction = "H", continent = 13 },
		{ name = "Grom'gol", npc = "Thysta", x = 39.01, y = 51.25, faction = "H", continent = 13 },
	},
	["ohn'ahran plains"] = {
		{ name = "Timberstep Outpost", npc = "Baqir", x = 85.28, y = 24.10, faction = "B", continent = 1978 },
		{ name = "Rusza'thar Reach", npc = "Malakesh", x = 84.66, y = 36.89, faction = "B", continent = 1978 },
		{ name = "Maruukai", npc = "Salukan", x = 62.96, y = 42.13, faction = "B", continent = 1978 },
		{ name = "Emberwatch", npc = "Volebel", x = 66.78, y = 25.17, faction = "B", continent = 1978 },
		{ name = "Broadhoof Outpost", npc = "Washengtu", x = 46.57, y = 41.29, faction = "B", continent = 1978 },
		{ name = "Shady Sanctuary", npc = "Sariosa", x = 29.82, y = 57.65, faction = "B", continent = 1978 },
		{ name = "Teerakai", npc = "Carseng", x = 39.98, y = 61.14, faction = "B", continent = 1978 },
		{ name = "Ohn'iri Springs", npc = "Huraq", x = 56.68, y = 76.59, faction = "B", continent = 1978 },
		{ name = "Forkriver Crossing", npc = "Rynaam", x = 71.65, y = 79.07, faction = "B", continent = 1978 },
		{ name = "Pinewood Post", npc = "Nakeena", x = 80.44, y = 57.89, faction = "B", continent = 1978 },
		{ name = "Rusza'thar Reach", npc = "Ancient Waygate", x = 81.31, y = 38.98, faction = "B", continent = 1978 },
		{ name = "Shady Sanctuary", npc = "Ancient Waygate", x = 30.66, y = 55.48, faction = "B", continent = 1978 },
		{ name = "Cascades Canyon, Ohn'ahran Plains", npc = "", x = 88.75, y = 27.66, faction = "B", continent = 1978 },
		{ name = "Old Loamm Road, Ohn'ahran Plains", npc = "", x = 36.02, y = 59.11, faction = "B", continent = 1978 },
	},
	["orgrimmar"] = {
		{ name = "Orgrimmar", npc = "Doras", x = 49.65, y = 59.21, faction = "H", continent = 12 },
	},
	["oribos"] = {
		{ name = "Oribos", npc = "Pathscribe Roh-Avonavi", x = 60.83, y = 68.60, faction = "B", continent = 1550 },
	},
	["razorwind shores"] = {
		{ name = "Entrance Gate", npc = "Thrauna", x = 54.78, y = 51.22, faction = "H", continent = 12 },
		{ name = "The Common", npc = "Broktar", x = 53.66, y = 59.72, faction = "H", continent = 12 },
		{ name = "Saltfang Shoals East", npc = "Trak Tuskbender", x = 68.09, y = 75.59, faction = "H", continent = 12 },
		{ name = "Runetotem's Bounty North", npc = "Zurlik", x = 42.70, y = 55.88, faction = "H", continent = 12 },
		{ name = "Runetotem's Bounty South", npc = "Reginald Glarestone", x = 47.77, y = 69.90, faction = "H", continent = 12 },
		{ name = "The Bluffs", npc = "Luk'gra", x = 52.71, y = 81.72, faction = "H", continent = 12 },
		{ name = "Cragthorn Highlands", npc = "Jarg Riverbender", x = 66.30, y = 56.55, faction = "H", continent = 12 },
		{ name = "The Bloom", npc = "Wuls", x = 59.21, y = 71.84, faction = "H", continent = 12 },
	},
	["redridge mountains"] = {
		{ name = "Camp Everstill", npc = "Arlen Marsters", x = 52.92, y = 54.64, faction = "A", continent = 13 },
		{ name = "Lakeshire", npc = "Ariena Stormfeather", x = 29.42, y = 53.76, faction = "A", continent = 13 },
		{ name = "Shalewind Canyon", npc = "Nora Baldwin", x = 77.97, y = 65.91, faction = "A", continent = 13 },
	},
	["revendreth"] = {
		{ name = "Pridefall Hamlet", npc = "Courier Gevoraal", x = 70.35, y = 81.16, faction = "B", continent = 1550 },
		{ name = "Darkhaven", npc = "Courier Rokalai", x = 60.50, y = 60.62, faction = "B", continent = 1550 },
		{ name = "Halls of Atonement", npc = "Courier Rehkaash", x = 71.58, y = 40.06, faction = "B", continent = 1550 },
		{ name = "Old Gate", npc = "Courier Tarehaar", x = 61.22, y = 38.79, faction = "B", continent = 1550 },
		{ name = "Menagerie of the Master", npc = "Courier Skraal", x = 54.22, y = 25.68, faction = "B", continent = 1550 },
		{ name = "Wanecrypt Hill", npc = "Courier Rabatur", x = 47.88, y = 69.40, faction = "B", continent = 1550 },
		{ name = "Charred Ramparts", npc = "Courier Chip", x = 38.95, y = 49.33, faction = "B", continent = 1550 },
		{ name = "Sanctuary of the Mad", npc = "Courier Shaal", x = 30.56, y = 48.88, faction = "B", continent = 1550 },
		{ name = "Dominance Keep", npc = "Courier Dreadcarrier", x = 25.96, y = 28.88, faction = "B", continent = 1550 },
	},
	["ruins of gilneas"] = {
		{ name = "Forsaken Forward Command", npc = "Bat Handler Doomair", x = 57.28, y = 17.75, faction = "H", continent = 13 },
	},
	["searing gorge"] = {
		{ name = "Thorium Point", npc = "Lanie Reed", x = 37.94, y = 30.86, faction = "A", continent = 13 },
		{ name = "Thorium Point", npc = "Grisha", x = 34.84, y = 30.88, faction = "H", continent = 13 },
		{ name = "Iron Summit", npc = "Doug Deepdown", x = 41.06, y = 68.78, faction = "B", continent = 13 },
	},
	["shadowmoon valley"] = {
		{ name = "Wildhammer Stronghold", npc = "Brubeck Stormfoot", x = 37.61, y = 55.45, faction = "A", continent = 101 },
		{ name = "Shadowmoon Village", npc = "Drek'Gol", x = 30.34, y = 29.19, faction = "H", continent = 101 },
		{ name = "Altar of Sha'tar", npc = "Maddix", x = 63.33, y = 30.40, faction = "B", continent = 101 },
		{ name = "Sanctum of the Stars", npc = "Alieshor", x = 56.32, y = 57.80, faction = "B", continent = 101 },
	},
	["shadowmoon valley d"] = {
		{ name = "Elodor", npc = "Vamuun", x = 58.68, y = 31.92, faction = "A", continent = 572 },
		{ name = "Path of Light", npc = "Paaya", x = 59.37, y = 45.98, faction = "A", continent = 572 },
		{ name = "Tranquil Court", npc = "Itara", x = 70.42, y = 50.42, faction = "A", continent = 572 },
		{ name = "The Draakorium", npc = "Morfax", x = 57.03, y = 56.63, faction = "A", continent = 572 },
		{ name = "Twilight Glade", npc = "Gotuun", x = 40.73, y = 55.28, faction = "A", continent = 572 },
		{ name = "Embaari Village", npc = "Eonor", x = 45.68, y = 38.86, faction = "A", continent = 572 },
		{ name = "Exile's Rise", npc = "Wargra", x = 45.57, y = 25.40, faction = "B", continent = 572 },
		{ name = "Socrethar's Rise", npc = "Azara Goldenwing", x = 43.89, y = 77.53, faction = "B", continent = 572 },
		{ name = "Darktide Roost", npc = "Beasttamer Ladaak", x = 59.85, y = 81.38, faction = "B", continent = 572 },
		{ name = "Temple of Karabor", npc = "", x = 0.00, y = 0.00, faction = "B", continent = 572 },
	},
	["shattrath city"] = {
		{ name = "Shattrath", npc = "Nutral", x = 64.07, y = 41.12, faction = "B", continent = 101 },
	},
	["shimmering expanse"] = {
		{ name = "Sandy Beach", npc = "Francis Greene", x = 57.04, y = 17.05, faction = "A", continent = 13 },
		{ name = "Tranquil Wash", npc = "Swift Seahorse", x = 48.55, y = 57.43, faction = "A", continent = 13 },
		{ name = "Voldrin's Hold", npc = "Salty McTavish", x = 56.77, y = 75.87, faction = "A", continent = 13 },
		{ name = "Voldrin's Hold", npc = "Swift Seahorse", x = 57.10, y = 75.17, faction = "A", continent = 13 },
		{ name = "Stygian Bounty", npc = "Brogdul", x = 50.23, y = 65.49, faction = "H", continent = 13 },
		{ name = "Stygian Bounty", npc = "Swift Seahorse", x = 49.47, y = 65.56, faction = "H", continent = 13 },
		{ name = "Sandy Beach", npc = "Briglar", x = 61.02, y = 28.43, faction = "H", continent = 13 },
		{ name = "Legion's Rest", npc = "Swift Seahorse", x = 50.74, y = 63.47, faction = "H", continent = 13 },
		{ name = "Silver Tide Hollow", npc = "Swift Seahorse", x = 49.52, y = 41.21, faction = "B", continent = 13 },
	},
	["sholazar basin"] = {
		{ name = "River's Heart", npc = "Marvin Wobblesprocket", x = 50.13, y = 61.36, faction = "B", continent = 113 },
		{ name = "Nesingwary Base Camp", npc = "The Spirit of Gnomeregan", x = 25.27, y = 58.44, faction = "B", continent = 113 },
	},
	["silithus"] = {
		{ name = "Cenarion Hold", npc = "Cloud Skydancer", x = 54.40, y = 32.72, faction = "A", continent = 12 },
		{ name = "Cenarion Hold", npc = "Runk Windtamer", x = 52.78, y = 34.64, faction = "H", continent = 12 },
	},
	["silvermoon city m"] = {
		{ name = "Sanctum of Light", npc = "Skymaster Skyles", x = 50.97, y = 71.25, faction = "B", continent = 13 },
		{ name = "The Royal Exchange", npc = "Anathos", x = 69.36, y = 63.31, faction = "H", continent = 13 },
	},
	["silverpine forest"] = {
		{ name = "The Forsaken Front", npc = "Steven Stutzka", x = 50.87, y = 63.62, faction = "H", continent = 13 },
		{ name = "The Sepulcher", npc = "Karos Razok", x = 45.41, y = 42.48, faction = "H", continent = 13 },
		{ name = "Forsaken Rear Guard", npc = "Franny Mertz", x = 45.93, y = 21.88, faction = "H", continent = 13 },
		{ name = "Forsaken High Command", npc = "Bat Handler Maggotbreath", x = 57.91, y = 8.70, faction = "H", continent = 13 },
	},
	["sinfall"] = {
		{ name = "Sinfall", npc = "Courier Snaggle", x = 67.31, y = 21.42, faction = "B", continent = 1550 },
	},
	["slayers rise"] = {
		{ name = "Master's Perch", npc = "Sayra Starreacher", x = 36.73, y = 83.86, faction = "B", continent = 2405 },
	},
	["southern barrens"] = {
		{ name = "Fort Triumph", npc = "Steve Stevenson", x = 49.20, y = 67.80, faction = "A", continent = 12 },
		{ name = "Honor's Stand", npc = "John Johnson", x = 38.93, y = 10.88, faction = "A", continent = 12 },
		{ name = "Northwatch Hold", npc = "Bill Williamson", x = 66.38, y = 47.13, faction = "A", continent = 12 },
		{ name = "Vendetta Point", npc = "Lognah", x = 41.55, y = 47.60, faction = "H", continent = 12 },
		{ name = "Desolation Hold", npc = "Crador", x = 41.24, y = 70.76, faction = "H", continent = 12 },
		{ name = "Hunter's Hill", npc = "Unega", x = 39.79, y = 20.26, faction = "H", continent = 12 },
	},
	["spires of arak"] = {
		{ name = "Southport", npc = "Fim Swiftbreeze", x = 39.08, y = 61.80, faction = "A", continent = 572 },
		{ name = "Axefall", npc = "Hutou Featherwind", x = 39.51, y = 43.37, faction = "H", continent = 572 },
		{ name = "Apexis Excavation", npc = "Skytalon Kuris", x = 36.99, y = 24.62, faction = "B", continent = 572 },
		{ name = "Crow's Crook", npc = "Darkscreech", x = 51.82, y = 31.05, faction = "B", continent = 572 },
		{ name = "Akeeta's Hovel", npc = "Duskclaw", x = 65.67, y = 17.51, faction = "B", continent = 572 },
		{ name = "Talon Watch", npc = "Skytalon Karaz", x = 61.90, y = 42.62, faction = "B", continent = 572 },
		{ name = "Pinchwhistle Gearworks", npc = "Kwiven Quickcog", x = 60.88, y = 73.30, faction = "B", continent = 572 },
		{ name = "Veil Terokk", npc = "Skytalon Meshaal", x = 46.17, y = 44.12, faction = "B", continent = 572 },
	},
	["stonetalon mountains"] = {
		{ name = "Farwatcher's Glen", npc = "Ceyora", x = 32.02, y = 61.84, faction = "A", continent = 12 },
		{ name = "Mirkfallon Post", npc = "Fiora Moonsoar", x = 48.64, y = 51.52, faction = "A", continent = 12 },
		{ name = "Northwatch Expedition Base Camp", npc = "Kaluna Songflight", x = 70.92, y = 80.58, faction = "A", continent = 12 },
		{ name = "Thal'darah Overlook", npc = "Teloren", x = 40.12, y = 31.96, faction = "A", continent = 12 },
		{ name = "Windshear Hold", npc = "Allana Swiftglide", x = 58.80, y = 54.28, faction = "A", continent = 12 },
		{ name = "Cliffwalker Post", npc = "Orna Skywatcher", x = 45.11, y = 30.87, faction = "H", continent = 12 },
		{ name = "Krom'gar Fortress", npc = "Kormal the Swift", x = 66.52, y = 62.75, faction = "H", continent = 12 },
		{ name = "Sun Rock Retreat", npc = "Tharm", x = 48.48, y = 61.95, faction = "H", continent = 12 },
		{ name = "The Sludgewerks", npc = "Flok", x = 53.87, y = 40.12, faction = "H", continent = 12 },
		{ name = "Malaka'jin", npc = "Zillane", x = 70.61, y = 89.46, faction = "H", continent = 12 },
	},
	["stormheim"] = {
		{ name = "Greywatch", npc = "Gryphon-Master Clifford", x = 72.15, y = 59.82, faction = "A", continent = 619 },
		{ name = "Lorna's Watch", npc = "Donovan", x = 37.41, y = 63.99, faction = "A", continent = 619 },
		{ name = "Skyfire Triage Camp", npc = "Donovan", x = 33.59, y = 50.65, faction = "A", continent = 619 },
		{ name = "Cullen's Post", npc = "Duchess", x = 44.89, y = 59.14, faction = "H", continent = 619 },
		{ name = "Dreadwake's Landing", npc = "Dread-Rider Barnes", x = 54.52, y = 73.03, faction = "H", continent = 619 },
		{ name = "Forsaken Foothold", npc = "Dread-Rider Roth", x = 36.49, y = 30.62, faction = "H", continent = 619 },
		{ name = "Hafr Fjall", npc = "Fluga the Scalekeeper", x = 55.63, y = 87.43, faction = "B", continent = 619 },
		{ name = "Shield's Rest", npc = "Visser the Scalekeeper", x = 89.87, y = 10.68, faction = "B", continent = 619 },
		{ name = "Valdisdall", npc = "Garhal the Scalekeeper", x = 60.73, y = 50.88, faction = "B", continent = 619 },
		{ name = "Stormtorn Foothills", npc = "Hillevi the Scalekeeper", x = 51.97, y = 34.81, faction = "B", continent = 619 },
	},
	["stormshield"] = {
		{ name = "Stormshield", npc = "Ernst ten Bosch", x = 30.57, y = 48.47, faction = "A", continent = 572 },
	},
	["stormsong valley"] = {
		{ name = "Millstone Hamlet", npc = "Alexa Davenport", x = 30.75, y = 66.57, faction = "A", continent = 876 },
		{ name = "Fort Daelin", npc = "Misty Koret", x = 34.28, y = 47.23, faction = "A", continent = 876 },
		{ name = "Deadwash", npc = "Malorian Tailwind", x = 42.77, y = 57.54, faction = "A", continent = 876 },
		{ name = "The Amber Waves", npc = "Karla Fairweather", x = 50.75, y = 70.21, faction = "A", continent = 876 },
		{ name = "Brennadam", npc = "Anna Skyspirit", x = 59.73, y = 70.56, faction = "A", continent = 876 },
		{ name = "Mildenhall Meadery", npc = "Colony Caretaker", x = 68.53, y = 64.99, faction = "A", continent = 876 },
		{ name = "Tidecross", npc = "Marla Featherfoot", x = 65.56, y = 48.00, faction = "A", continent = 876 },
		{ name = "Shrine of the Storm", npc = "Galeheart", x = 78.32, y = 29.00, faction = "A", continent = 876 },
		{ name = "Seekers Vista", npc = "Scroll of Flight", x = 40.03, y = 37.32, faction = "B", continent = 876 },
		{ name = "Warfang Hold", npc = "Muka Stormbreaker", x = 51.42, y = 33.74, faction = "H", continent = 876 },
		{ name = "Hillcrest Pasture", npc = "Hosan Cloudhoof", x = 52.76, y = 80.13, faction = "H", continent = 876 },
		{ name = "Ironmaul Overlook", npc = "Chulani Cloudbreath", x = 75.88, y = 64.14, faction = "H", continent = 876 },
		{ name = "Shrine of the Storm", npc = "Dark Ranger Allanah", x = 77.90, y = 24.07, faction = "H", continent = 876 },
		{ name = "Diretusk Hollow", npc = "Kudra Windblade", x = 54.27, y = 49.35, faction = "H", continent = 876 },
		{ name = "Windfall Cavern", npc = "Allabas", x = 60.84, y = 27.12, faction = "H", continent = 876 },
		{ name = "Stonetusk Watch", npc = "Wyna Breezehorn", x = 38.84, y = 66.64, faction = "H", continent = 876 },
	},
	["stormwind city"] = {
		{ name = "Stormwind", npc = "Dungar Longdrink", x = 70.94, y = 72.46, faction = "A", continent = 13 },
	},
	["suramar"] = {
		{ name = "Meredil", npc = "Ancient Cloudwing", x = 34.38, y = 49.41, faction = "B", continent = 619 },
		{ name = "Irongrove Retreat", npc = "Alyndra Stormgazer", x = 25.46, y = 31.73, faction = "B", continent = 619 },
		{ name = "Crimson Thicket", npc = "Ancient Cloudwing", x = 64.27, y = 41.98, faction = "B", continent = 619 },
	},
	["swamp of sorrows"] = {
		{ name = "Marshtide Watch", npc = "Paola Baldwin", x = 70.05, y = 38.57, faction = "A", continent = 13 },
		{ name = "The Harborage", npc = "Yedrin", x = 30.78, y = 34.60, faction = "A", continent = 13 },
		{ name = "Stonard", npc = "Breyk", x = 47.78, y = 55.22, faction = "H", continent = 13 },
		{ name = "Bogpaddle", npc = "Skeezie", x = 72.02, y = 12.04, faction = "B", continent = 13 },
	},
	["talador"] = {
		{ name = "Exarch's Refuge", npc = "Niaa", x = 54.79, y = 68.79, faction = "A", continent = 572 },
		{ name = "Anchorite's Sojourn", npc = "Zaari", x = 80.08, y = 56.68, faction = "A", continent = 572 },
		{ name = "Fort Wrynn", npc = "Skyguard Amelia", x = 69.86, y = 21.49, faction = "A", continent = 572 },
		{ name = "Redemption Rise", npc = "Nomaeaa", x = 63.29, y = 25.72, faction = "A", continent = 572 },
		{ name = "Frostwolf Overlook", npc = "Mok'ra", x = 61.41, y = 10.51, faction = "H", continent = 572 },
		{ name = "Vol'jin's Pride", npc = "Mo'jimba", x = 70.74, y = 29.40, faction = "H", continent = 572 },
		{ name = "Durotan's Grasp", npc = "Tega Skyblade", x = 55.42, y = 40.82, faction = "H", continent = 572 },
		{ name = "Exarch's Refuge", npc = "Roka", x = 54.54, y = 67.82, faction = "H", continent = 572 },
		{ name = "Retribution Point", npc = "Beldos", x = 42.11, y = 76.79, faction = "B", continent = 572 },
		{ name = "Shattrath City", npc = "Zamara", x = 51.27, y = 42.66, faction = "B", continent = 572 },
		{ name = "Terokkar Refuge", npc = "Skytalon Inuz", x = 70.34, y = 57.10, faction = "B", continent = 572 },
		{ name = "Zangarra", npc = "Dominic Arlington", x = 80.42, y = 25.32, faction = "B", continent = 572 },
	},
	["tanaan jungle"] = {
		{ name = "Lion's Watch", npc = "Skyguard Thann", x = 57.51, y = 58.76, faction = "A", continent = 572 },
		{ name = "The Iron Front", npc = "Skyguard Blann", x = 10.03, y = 53.07, faction = "A", continent = 572 },
		{ name = "The Iron Front", npc = "Nasher", x = 9.27, y = 55.86, faction = "H", continent = 572 },
		{ name = "Vol'mar", npc = "Gargash the Diver", x = 60.43, y = 46.44, faction = "H", continent = 572 },
		{ name = "Aktar's Post", npc = "Skytalon Kariz", x = 26.14, y = 38.88, faction = "B", continent = 572 },
		{ name = "Sha'naari Refuge", npc = "Rangari Sha'ana", x = 29.55, y = 63.14, faction = "B", continent = 572 },
		{ name = "Malo's Lookout", npc = "Rocketmaster Malo", x = 43.40, y = 42.24, faction = "B", continent = 572 },
		{ name = "Vault of the Earth", npc = "Urtol Skyshear", x = 47.00, y = 70.26, faction = "B", continent = 572 },
	},
	["tanaris"] = {
		{ name = "Gunstan's Dig", npc = "Thurda", x = 40.05, y = 77.54, faction = "A", continent = 12 },
		{ name = "Gadgetzan", npc = "Bera Stonehammer", x = 51.35, y = 29.49, faction = "A", continent = 12 },
		{ name = "Dawnrise Expedition", npc = "Raina Sunglide", x = 33.30, y = 77.36, faction = "H", continent = 12 },
		{ name = "Gadgetzan", npc = "Bulkrek Ragefist", x = 52.04, y = 27.61, faction = "H", continent = 12 },
		{ name = "Bootlegger Outpost", npc = "Slick Dropdip", x = 55.88, y = 60.60, faction = "B", continent = 12 },
	},
	["tazavesh"] = {
		{ name = "Tazavesh", npc = "Om'thenai", x = 34.75, y = 10.03, faction = "B", continent = 2274 },
		{ name = "Tazavesh", npc = "Phase Conduit", x = 46.78, y = 56.79, faction = "B", continent = 2274 },
	},
	["teldrassil"] = {
		{ name = "Dolanaar", npc = "Fidelio", x = 55.47, y = 50.42, faction = "A", continent = 12 },
		{ name = "Rut'theran Village", npc = "Vesprystus", x = 55.41, y = 88.40, faction = "A", continent = 12 },
	},
	["terokkar forest"] = {
		{ name = "Allerian Stronghold", npc = "Furnan Skysoar", x = 59.45, y = 55.43, faction = "A", continent = 101 },
		{ name = "Stonebreaker Hold", npc = "Kerna", x = 49.19, y = 43.42, faction = "H", continent = 101 },
		{ name = "Blackwing Landing", npc = "Skyguard Handler Deesak", x = 63.50, y = 65.81, faction = "B", continent = 101 },
	},
	["thaldraszus"] = {
		{ name = "Garden Shrine", npc = "Valdren", x = 35.62, y = 78.86, faction = "B", continent = 1978 },
		{ name = "Gelikyr Post", npc = "Talon Smoht", x = 51.16, y = 67.08, faction = "B", continent = 1978 },
		{ name = "Shifting Sands", npc = "Azim", x = 57.63, y = 79.02, faction = "B", continent = 1978 },
		{ name = "Temporal Conflux", npc = "Warden Dialash", x = 59.91, y = 81.34, faction = "B", continent = 1978 },
		{ name = "Vault of the Incarnates", npc = "Nirazal", x = 72.14, y = 56.45, faction = "B", continent = 1978 },
		{ name = "Veiled Ossuary", npc = "Officer Obernax", x = 62.07, y = 18.93, faction = "B", continent = 1978 },
		{ name = "Algeth'era", npc = "Vesri", x = 49.47, y = 41.95, faction = "B", continent = 1978 },
		{ name = "Algeth'era", npc = "Ancient Waygate", x = 62.42, y = 40.47, faction = "B", continent = 1978 },
		{ name = "Eon's Fringe", npc = "Ancient Waygate", x = 52.34, y = 78.54, faction = "B", continent = 1978 },
	},
	["the azure span"] = {
		{ name = "Cobalt Assembly", npc = "Kruthix", x = 49.10, y = 22.67, faction = "B", continent = 1978 },
		{ name = "Camp Antonidas", npc = "Steward Argalos", x = 46.71, y = 39.56, faction = "B", continent = 1978 },
		{ name = "Three-Falls Lookout", npc = "Bergede Broadchin", x = 19.15, y = 23.78, faction = "B", continent = 1978 },
		{ name = "Iskaara", npc = "Skygazer Paatu", x = 13.29, y = 48.77, faction = "B", continent = 1978 },
		{ name = "Azure Archives", npc = "Arc Tel XVII", x = 37.06, y = 60.82, faction = "B", continent = 1978 },
		{ name = "Camp Nowhere", npc = "Camilla Highwind", x = 63.45, y = 58.67, faction = "B", continent = 1978 },
		{ name = "Rhonin's Shield", npc = "Portia Striat", x = 66.00, y = 25.39, faction = "B", continent = 1978 },
		{ name = "Theron's Watch", npc = "Taelmyr Blazewing", x = 65.37, y = 16.39, faction = "B", continent = 1978 },
		{ name = "Cobalt Assembly", npc = "Ancient Waygate", x = 48.33, y = 30.13, faction = "B", continent = 1978 },
		{ name = "Vakthros", npc = "Ancient Waygate", x = 77.59, y = 30.79, faction = "B", continent = 1978 },
		{ name = "Lookout Breach, Azure Span", npc = "", x = 18.75, y = 22.87, faction = "B", continent = 1978 },
	},
	["the cape of stranglethorn"] = {
		{ name = "Booty Bay", npc = "Gyll", x = 41.67, y = 74.53, faction = "A", continent = 13 },
		{ name = "Explorers' League Digsite", npc = "Colin Swifthammer", x = 55.74, y = 41.22, faction = "A", continent = 13 },
		{ name = "Booty Bay", npc = "Gringer", x = 40.61, y = 73.42, faction = "H", continent = 13 },
		{ name = "Hardwrench Hideaway", npc = "Hizzle", x = 35.14, y = 29.39, faction = "H", continent = 13 },
	},
	["the dreamgrove"] = {
		{ name = "The Dreamgrove", npc = "Danise Stargazer", x = 61.73, y = 33.99, faction = "B", continent = 619 },
	},
	["the emerald dream"] = {
		{ name = "Verdant Landing", npc = "Occarim", x = 68.82, y = 54.79, faction = "B", continent = 1978 },
		{ name = "Wellspring Overlook", npc = "Thevelo", x = 35.65, y = 33.66, faction = "B", continent = 1978 },
		{ name = "Central Encampment", npc = "Leora", x = 51.09, y = 62.35, faction = "B", continent = 1978 },
		{ name = "Eye of Ysera", npc = "Eladriel", x = 55.29, y = 29.57, faction = "B", continent = 1978 },
	},
	["the exodar"] = {
		{ name = "The Exodar", npc = "Stephanos", x = 54.49, y = 36.27, faction = "A", continent = 12 },
	},
	["the forbidden reach/5"] = {
		{ name = "Morqut Village", npc = "Renpiaq", x = 35.85, y = 59.12, faction = "B", continent = 1978 },
		{ name = "Morqut Islet", npc = "Ancient Waygate", x = 29.08, y = 62.45, faction = "B", continent = 1978 },
	},
	["the gilded landing"] = {
		{ name = "Tazavesh", npc = "Ta'resarra", x = 91.96, y = 41.71, faction = "B", continent = 1550 },
	},
	["the hinterlands"] = {
		{ name = "Aerie Peak", npc = "Guthrum Thunderfist", x = 11.07, y = 46.15, faction = "A", continent = 13 },
		{ name = "Stormfeather Outpost", npc = "Brock Rockbeard", x = 65.77, y = 44.87, faction = "A", continent = 13 },
		{ name = "Hiri'watha Research Station", npc = "Kellen Kuhn", x = 32.45, y = 58.08, faction = "H", continent = 13 },
		{ name = "Revantusk Village", npc = "Gorkas", x = 81.71, y = 81.75, faction = "H", continent = 13 },
	},
	["the jade forest"] = {
		{ name = "Paw'Don Village", npc = "Wing Kyo", x = 46.04, y = 85.15, faction = "A", continent = 424 },
		{ name = "Pearlfin Village", npc = "Ut-Nam", x = 57.95, y = 82.51, faction = "A", continent = 424 },
		{ name = "Honeydew Village", npc = "Wing Hya", x = 28.11, y = 15.62, faction = "H", continent = 424 },
		{ name = "Grookin Hill", npc = "Grookin Flapmaster", x = 27.81, y = 47.91, faction = "H", continent = 424 },
		{ name = "Serpent's Overlook", npc = "Sky Dancer Ji", x = 43.10, y = 68.49, faction = "B", continent = 424 },
		{ name = "Sri-La Village", npc = "Gingo Alebottom", x = 55.38, y = 23.73, faction = "B", continent = 424 },
		{ name = "Emperor's Omen", npc = "Supplier Towsa", x = 50.82, y = 26.80, faction = "B", continent = 424 },
		{ name = "Tian Monastery", npc = "Studious Chu", x = 43.57, y = 24.53, faction = "B", continent = 424 },
		{ name = "Dawn's Blossom", npc = "Keg Runner Lee", x = 47.05, y = 46.24, faction = "B", continent = 424 },
		{ name = "The Arboretum", npc = "Injar'i Lakebloom", x = 57.01, y = 44.03, faction = "B", continent = 424 },
		{ name = "Jade Temple Grounds", npc = "Ginsa Arroweye", x = 54.57, y = 61.76, faction = "B", continent = 424 },
	},
	["the maw"] = {
		{ name = "Ve'nari's Refuge", npc = "Animaflow Teleporter", x = 47.29, y = 43.67, faction = "B", continent = 1550 },
	},
	["the ringing deeps"] = {
		{ name = "Gundargaz", npc = "Igram Underwing", x = 42.71, y = 33.36, faction = "B", continent = 2274 },
		{ name = "Shadowvein Point", npc = "Milgrit Stonefeather", x = 57.28, y = 47.94, faction = "B", continent = 2274 },
		{ name = "Camp Murroch", npc = "Kargen Ironbrow", x = 54.01, y = 64.05, faction = "B", continent = 2274 },
		{ name = "Opportunity Point", npc = "Clixi Fastfare", x = 60.55, y = 78.08, faction = "B", continent = 2274 },
		{ name = "Gutterville", npc = "Jix", x = 71.52, y = 83.35, faction = "B", continent = 2274 },
	},
	["the storm peaks"] = {
		{ name = "Frosthold", npc = "Faldorf Bitterchill", x = 29.50, y = 74.33, faction = "A", continent = 113 },
		{ name = "Grom'arsh Crash-Site", npc = "Kabarg Windtamer", x = 36.19, y = 49.39, faction = "H", continent = 113 },
		{ name = "Camp Tunka'lo", npc = "Hyeyoung Parka", x = 65.41, y = 50.60, faction = "H", continent = 113 },
		{ name = "K3", npc = "Skizzle Slickslide", x = 40.75, y = 84.55, faction = "B", continent = 113 },
		{ name = "Dun Niffelem", npc = "Halvdan", x = 62.63, y = 60.93, faction = "B", continent = 113 },
		{ name = "Ulduar", npc = "Shavalius the Fancy", x = 44.49, y = 28.19, faction = "B", continent = 113 },
		{ name = "Bouldercrag's Refuge", npc = "Breck Rockbrow", x = 30.65, y = 36.32, faction = "B", continent = 113 },
	},
	["the veiled stair"] = {
		{ name = "Tavern in the Mists", npc = "Shin the Weightless", x = 56.74, y = 75.75, faction = "B", continent = 424 },
	},
	["the waking shores"] = {
		{ name = "Wingrest Embassy", npc = "Tixxa Mixxa", x = 76.03, y = 35.05, faction = "B", continent = 1978 },
		{ name = "Uktulut Pier", npc = "Pana", x = 45.84, y = 27.48, faction = "B", continent = 1978 },
		{ name = "Uktulut Backwater", npc = "Janatak", x = 54.32, y = 36.97, faction = "B", continent = 1978 },
		{ name = "Skytop Observatory", npc = "Azerastrasz", x = 72.77, y = 51.91, faction = "B", continent = 1978 },
		{ name = "Life Vault Ruins", npc = "Tallevia Mistsong", x = 65.03, y = 57.36, faction = "B", continent = 1978 },
		{ name = "Ruby Life Pools", npc = "Vaknai", x = 57.80, y = 68.12, faction = "B", continent = 1978 },
		{ name = "Dragonscale Basecamp", npc = "Art Raskins", x = 47.91, y = 83.32, faction = "B", continent = 1978 },
		{ name = "Obsidian Bulwark", npc = "Do-Yeon Shadowrider", x = 42.26, y = 66.25, faction = "B", continent = 1978 },
		{ name = "Obsidian Throne", npc = "Foehn Breezeskimmer", x = 25.27, y = 56.83, faction = "B", continent = 1978 },
		{ name = "Apex Observatory", npc = "Hjorik", x = 23.79, y = 83.14, faction = "B", continent = 1978 },
		{ name = "Uktulut Outpost", npc = "Nulia", x = 17.51, y = 88.70, faction = "B", continent = 1978 },
		{ name = "Skytop Observatory", npc = "Ancient Waygate", x = 75.28, y = 57.02, faction = "B", continent = 1978 },
		{ name = "Rubyscale Outpost", npc = "Ancient Waygate", x = 47.28, y = 90.30, faction = "B", continent = 1978 },
	},
	["thousand needles"] = {
		{ name = "Fizzle & Pozzik's Speedbarge", npc = "Tilly Topspin", x = 79.15, y = 71.95, faction = "A", continent = 12 },
		{ name = "Fizzle & Pozzik's Speedbarge", npc = "Zazzix Boomride", x = 79.19, y = 71.89, faction = "H", continent = 12 },
		{ name = "Westreach Summit", npc = "Nah'te", x = 11.21, y = 11.58, faction = "H", continent = 12 },
	},
	["thunder bluff"] = {
		{ name = "Thunder Bluff", npc = "Tal", x = 47.02, y = 49.60, faction = "H", continent = 12 },
	},
	["thunder totem"] = {
		{ name = "Thunder Totem", npc = "Windtamer Nalt", x = 44.75, y = 38.55, faction = "B", continent = 619 },
	},
	["timeless isle"] = {
		{ name = "Tushui Landing", npc = "Michi Windblossom", x = 23.08, y = 71.05, faction = "A", continent = 424 },
		{ name = "Huojin Landing", npc = "Chi-Ro the Skytamer", x = 21.92, y = 39.75, faction = "H", continent = 424 },
	},
	["tiragarde sound"] = {
		{ name = "Bridgeport", npc = "Jeb Johnson", x = 75.79, y = 48.59, faction = "A", continent = 876 },
		{ name = "Kennings Lodge", npc = "Finnia Hawkshot", x = 76.67, y = 65.42, faction = "A", continent = 876 },
		{ name = "Vigil Hill", npc = "Sky Marshal Sanders", x = 57.74, y = 61.54, faction = "A", continent = 876 },
		{ name = "Hatherford", npc = "Mariah McKee", x = 66.93, y = 23.06, faction = "A", continent = 876 },
		{ name = "Norwington Estate", npc = "Hestia Strongbolt", x = 52.91, y = 28.80, faction = "A", continent = 876 },
		{ name = "Roughneck Camp", npc = "Dagin", x = 42.48, y = 23.02, faction = "A", continent = 876 },
		{ name = "Outrigger Post", npc = "Gregory Mussler", x = 35.55, y = 24.90, faction = "A", continent = 876 },
		{ name = "Castaway Point", npc = "Skinny Tim", x = 86.42, y = 80.81, faction = "B", continent = 876 },
		{ name = "Freehold", npc = "Rodrigo", x = 77.03, y = 82.89, faction = "B", continent = 876 },
		{ name = "Eastpoint Station", npc = "Rosha Carrol", x = 74.23, y = 44.34, faction = "A", continent = 876 },
		{ name = "Southwind Ferry Dock", npc = "Bindy Bracklesprig", x = 66.74, y = 49.76, faction = "A", continent = 876 },
		{ name = "Old Drust Road", npc = "Theresa Norman", x = 54.01, y = 53.21, faction = "A", continent = 876 },
		{ name = "Anglepoint Wharf", npc = "Barry Oliver", x = 42.15, y = 30.67, faction = "A", continent = 876 },
		{ name = "Firebreaker Expedition", npc = "Joshua Neeman", x = 63.84, y = 30.38, faction = "A", continent = 876 },
		{ name = "Plunder Harbor", npc = "Skrash", x = 87.28, y = 50.66, faction = "H", continent = 876 },
		{ name = "Timberfell Outpost", npc = "Michaela Reed", x = 72.18, y = 51.91, faction = "H", continent = 876 },
		{ name = "Waning Glacier", npc = "Kip Wingnut", x = 39.68, y = 18.54, faction = "H", continent = 876 },
		{ name = "Wolf's Den", npc = "Narkalt", x = 62.11, y = 13.57, faction = "H", continent = 876 },
		{ name = "Stonefist Watch", npc = "Munovuth Boldcleaver", x = 53.14, y = 63.16, faction = "H", continent = 876 },
	},
	["tirisfal glades"] = {
		{ name = "Brill", npc = "Anette Williams", x = 58.84, y = 51.94, faction = "H", continent = 13 },
		{ name = "The Bulwark", npc = "Timothy Cunningham", x = 83.58, y = 69.95, faction = "H", continent = 13 },
	},
	["tirisfal glades l"] = {
		{ name = "Brill", npc = "Anette Williams", x = 58.76, y = 51.88, faction = "H", continent = 13 },
	},
	["tol dagor isle"] = {
		{ name = "Tol Dagor", npc = "Jorum Hayes", x = 38.00, y = 92.00, faction = "A", continent = 876 },
		{ name = "Tol Dagor", npc = "Erika Jones", x = 23.21, y = 47.98, faction = "H", continent = 876 },
	},
	["townlong steppes"] = {
		{ name = "Longying Outpost", npc = "Kite Master Wong", x = 71.08, y = 57.32, faction = "B", continent = 424 },
		{ name = "Gao-Ran Battlefront", npc = "Kite Master Nenshi", x = 74.39, y = 81.46, faction = "B", continent = 424 },
		{ name = "Rensai's Watchpost", npc = "Kite Master Li-Sen", x = 54.29, y = 79.05, faction = "B", continent = 424 },
		{ name = "Shado-Pan Garrison", npc = "Kite Master Yao-Li", x = 50.08, y = 71.98, faction = "B", continent = 424 },
	},
	["trueshot lodge"] = {
		{ name = "Trueshot Lodge", npc = "Odan Battlebow", x = 35.80, y = 27.58, faction = "B", continent = 619 },
	},
	["twilight highlands"] = {
		{ name = "Firebeard's Patrol", npc = "Farstad Stonegrip", x = 60.42, y = 57.65, faction = "A", continent = 13 },
		{ name = "Highbank", npc = "Glenn Arbuckle", x = 81.66, y = 77.12, faction = "A", continent = 13 },
		{ name = "Kirthaven", npc = "Shaina Talonheart", x = 56.78, y = 15.11, faction = "A", continent = 13 },
		{ name = "Thundermar", npc = "Doran Talonheart", x = 48.54, y = 28.10, faction = "A", continent = 13 },
		{ name = "Victor's Point", npc = "Desmond Chadsworth", x = 43.89, y = 57.27, faction = "A", continent = 13 },
		{ name = "Bloodgulch", npc = "Bramok Gorewing", x = 54.15, y = 42.22, faction = "H", continent = 13 },
		{ name = "Crushblow", npc = "Tokrog", x = 45.76, y = 76.19, faction = "H", continent = 13 },
		{ name = "Dragonmaw Port", npc = "Gorthul", x = 73.79, y = 52.80, faction = "H", continent = 13 },
		{ name = "The Gullet", npc = "San'shigo", x = 36.90, y = 37.99, faction = "H", continent = 13 },
		{ name = "The Krazzworks", npc = "Harpo Boltknuckle", x = 75.33, y = 17.79, faction = "H", continent = 13 },
		{ name = "Vermillion Redoubt", npc = "Aquinastrasz", x = 28.55, y = 24.86, faction = "B", continent = 13 },
	},
	["uldum"] = {
		{ name = "Oasis of Vir'sar", npc = "Jock Lindsey", x = 26.61, y = 8.38, faction = "B", continent = 12 },
		{ name = "Ramkahen", npc = "Kurzel", x = 56.19, y = 33.60, faction = "B", continent = 12 },
		{ name = "Schnottz's Landing", npc = "Evax Oilspark", x = 22.29, y = 64.93, faction = "B", continent = 12 },
	},
	["uldum new"] = {
		{ name = "Oasis of Vir'sar", npc = "Jock Lindsey", x = 26.61, y = 8.38, faction = "B", continent = 12 },
		{ name = "Ramkahen", npc = "Kurzel", x = 56.19, y = 33.60, faction = "B", continent = 12 },
	},
	["un'goro crater"] = {
		{ name = "Marshal's Stand", npc = "Gryfe", x = 55.98, y = 64.17, faction = "B", continent = 12 },
		{ name = "Mossy Pile", npc = "Flizzy Coilspanner", x = 44.11, y = 40.28, faction = "B", continent = 12 },
	},
	["undercity"] = {
		{ name = "Undercity", npc = "Michael Garrett", x = 63.26, y = 48.55, faction = "H", continent = 13 },
	},
	["undermine"] = {
		{ name = "Slam Central Station", npc = "Tommy Quickshot", x = 24.47, y = 52.40, faction = "B", continent = 2374 },
		{ name = "The Incontinental Hotel", npc = "Mozzik", x = 43.01, y = 45.98, faction = "B", continent = 2374 },
		{ name = "The Heaps", npc = "Twixki Gearshot", x = 43.68, y = 79.28, faction = "B", continent = 2374 },
		{ name = "Demolition Dome", npc = "Jenni Cogshatter", x = 24.47, y = 58.02, faction = "B", continent = 2374 },
		{ name = "The Gallagio", npc = "Technician Rinklefuse", x = 61.68, y = 48.16, faction = "B", continent = 2374 },
	},
	["val'sharah"] = {
		{ name = "Bradensbrook", npc = "Douglas Carrington", x = 42.23, y = 58.48, faction = "B", continent = 619 },
		{ name = "Garden of the Moon", npc = "Brinlanya Moonstone", x = 56.74, y = 57.72, faction = "B", continent = 619 },
		{ name = "Lorlathil", npc = "Elyssia Winterdusk", x = 54.98, y = 72.47, faction = "B", continent = 619 },
		{ name = "Starsong Refuge", npc = "Landrius Ravenfall", x = 69.02, y = 50.83, faction = "B", continent = 619 },
		{ name = "Gloaming Reef", npc = "Gyrdaen Windreef", x = 25.91, y = 66.52, faction = "B", continent = 619 },
	},
	["valdrakken"] = {
		{ name = "Valdrakken", npc = "Aluri", x = 44.04, y = 67.97, faction = "B", continent = 1978 },
	},
	["vale of eternal blossoms"] = {
		{ name = "Shrine of Seven Stars", npc = "Sharinga Springrunner", x = 84.61, y = 62.41, faction = "A", continent = 424 },
		{ name = "The Lion's Redoubt", npc = "Tiper Windman", x = 11.11, y = 101.67, faction = "A", continent = 424 },
		{ name = "Shrine of Two Moons", npc = "Tania Summerbreeze", x = 62.86, y = 21.80, faction = "H", continent = 424 },
		{ name = "Serpent's Spine", npc = "Mai of the Wall", x = 14.22, y = 79.28, faction = "B", continent = 424 },
	},
	["vale of eternal blossoms new"] = {
		{ name = "The Summer Terrace", npc = "Sharinga Springrunner", x = 85.17, y = 60.31, faction = "A", continent = 424 },
		{ name = "The Golden Terrace", npc = "Tania Summerbreeze", x = 63.11, y = 19.19, faction = "H", continent = 424 },
		{ name = "Mistfall Village", npc = "Ryuxi", x = 38.91, y = 72.80, faction = "B", continent = 424 },
	},
	["valley of the four winds"] = {
		{ name = "Pang's Stead", npc = "Princeton", x = 84.50, y = 21.06, faction = "B", continent = 424 },
		{ name = "Grassy Cline", npc = "Kim of the Mountain Winds", x = 70.82, y = 24.10, faction = "B", continent = 424 },
		{ name = "Halfhill", npc = "Wing Nga", x = 56.50, y = 50.36, faction = "B", continent = 424 },
		{ name = "Stoneplow", npc = "\"Dragonwing\" Dan", x = 20.30, y = 58.68, faction = "B", continent = 424 },
	},
	["voidstorm"] = {
		{ name = "The Ingress", npc = "Severenar Stargazer", x = 36.91, y = 58.98, faction = "B", continent = 2405 },
		{ name = "Locus Point", npc = "Vyana Vespersong", x = 42.29, y = 73.73, faction = "B", continent = 2405 },
		{ name = "Howling Ridge", npc = "Riftwalker Malloril", x = 51.14, y = 69.26, faction = "B", continent = 2405 },
	},
	["vol'dun"] = {
		{ name = "Vorrik's Sanctum", npc = "Lugo the Windrider", x = 47.30, y = 35.23, faction = "H", continent = 875 },
		{ name = "Vulpera Hideaway", npc = "Narishi", x = 56.96, y = 49.25, faction = "H", continent = 875 },
		{ name = "Goldtusk Inn", npc = "Volni", x = 42.74, y = 61.08, faction = "H", continent = 875 },
		{ name = "Scorched Sands Outpost", npc = "Makaanji", x = 43.90, y = 75.92, faction = "H", continent = 875 },
		{ name = "Temple of Akunda", npc = "Sejiju", x = 53.72, y = 89.18, faction = "H", continent = 875 },
		{ name = "Shatterstone Harbor", npc = "Barnard \"the Smasherr\" Baysworth", x = 36.68, y = 34.28, faction = "A", continent = 875 },
		{ name = "Deadwood Cove", npc = "Explosioneer Zoidfuse", x = 39.79, y = 83.82, faction = "A", continent = 875 },
		{ name = "Vulture's Nest", npc = "Buzz Crankchug", x = 53.60, y = 37.67, faction = "A", continent = 875 },
		{ name = "Tortaka Refuge", npc = "Scroll of Flight", x = 61.90, y = 21.66, faction = "B", continent = 875 },
		{ name = "Sanctuary of the Devoted", npc = "Vethiss", x = 27.65, y = 50.33, faction = "B", continent = 875 },
	},
	["warspear"] = {
		{ name = "Warspear", npc = "Ilalu", x = 44.15, y = 33.87, faction = "H", continent = 572 },
	},
	["western plaguelands"] = {
		{ name = "Andorhal", npc = "Ginny Goodwin", x = 39.43, y = 69.55, faction = "A", continent = 13 },
		{ name = "Chillwind Camp", npc = "Bibilfaz Featherwhistle", x = 42.92, y = 85.06, faction = "A", continent = 13 },
		{ name = "Andorhal", npc = "Rhonda Molver", x = 46.52, y = 64.71, faction = "H", continent = 13 },
		{ name = "Hearthglen", npc = "William Henderson", x = 44.66, y = 18.47, faction = "B", continent = 13 },
		{ name = "The Menders' Stead", npc = "Marge Heffman", x = 50.50, y = 52.23, faction = "B", continent = 13 },
	},
	["westfall"] = {
		{ name = "Sentinel Hill", npc = "Thor", x = 56.64, y = 49.44, faction = "A", continent = 13 },
		{ name = "Moonbrook", npc = "Tina Skyden", x = 42.08, y = 63.28, faction = "A", continent = 13 },
		{ name = "Furlbrow's Pumpkin Farm", npc = "Hoboair", x = 49.79, y = 18.69, faction = "A", continent = 13 },
	},
	["wetlands"] = {
		{ name = "Dun Modr", npc = "Caleb Baelor", x = 49.90, y = 18.56, faction = "A", continent = 13 },
		{ name = "Greenwarden's Grove", npc = "Halana", x = 56.31, y = 41.85, faction = "A", continent = 13 },
		{ name = "Menethil Harbor", npc = "Shellei Brondir", x = 9.45, y = 59.58, faction = "A", continent = 13 },
		{ name = "Slabchisel's Survey", npc = "Elgin Baelor", x = 56.87, y = 71.10, faction = "A", continent = 13 },
		{ name = "Whelgar's Retreat", npc = "Damon Baelor", x = 38.78, y = 39.04, faction = "A", continent = 13 },
	},
	["wintergrasp"] = {
		{ name = "Valiance Landing Camp", npc = "Arzo Safeflight", x = 71.98, y = 30.95, faction = "A", continent = 113 },
		{ name = "Warsong Camp", npc = "Herzo Safeflight", x = 21.62, y = 34.95, faction = "H", continent = 113 },
	},
	["winterspring"] = {
		{ name = "Everlook", npc = "Maethrya", x = 60.99, y = 48.62, faction = "A", continent = 12 },
		{ name = "Everlook", npc = "Yugrek", x = 58.84, y = 48.26, faction = "H", continent = 12 },
	},
	["zangarmarsh"] = {
		{ name = "Orebor Harborage", npc = "Halu", x = 41.28, y = 29.00, faction = "A", continent = 101 },
		{ name = "Telredor", npc = "Munci", x = 67.83, y = 51.46, faction = "A", continent = 101 },
		{ name = "Swamprat Post", npc = "Gur'zil", x = 84.76, y = 55.11, faction = "H", continent = 101 },
		{ name = "Zabra'jin", npc = "Du'ga", x = 33.07, y = 51.07, faction = "H", continent = 101 },
	},
	["zaralek cavern"] = {
		{ name = "Obsidian Rest", npc = "Keskos", x = 51.03, y = 26.17, faction = "B", continent = 1978 },
		{ name = "Loamm", npc = "Avogadro", x = 55.64, y = 54.79, faction = "B", continent = 1978 },
		{ name = "Dragonscale Camp", npc = "Sharpbeak", x = 40.34, y = 67.80, faction = "B", continent = 1978 },
		{ name = "The Throughway, Zaralek Cavern", npc = "", x = 73.80, y = 49.33, faction = "B", continent = 1978 },
		{ name = "Old Loamm Road, Zaralek Cavern", npc = "", x = 34.50, y = 79.60, faction = "B", continent = 1978 },
		{ name = "Lookout Breach, Zaralek Cavern", npc = "", x = 35.80, y = 89.80, faction = "B", continent = 1978 },
	},
	["zereth mortis"] = {
		{ name = "Haven", npc = "Ancient Translocator", x = 35.75, y = 65.11, faction = "B", continent = 1970 },
		{ name = "Faith's Repose", npc = "Ancient Translocator", x = 35.62, y = 44.33, faction = "B", continent = 1970 },
		{ name = "Pilgrim's Grace", npc = "Ancient Translocator", x = 61.61, y = 50.21, faction = "B", continent = 1970 },
		{ name = "Zovaal's Grasp", npc = "Ancient Translocator", x = 46.09, y = 21.62, faction = "B", continent = 1970 },
		{ name = "Antecedent Isle", npc = "Ancient Translocator", x = 47.36, y = 13.29, faction = "B", continent = 1970 },
		{ name = "Sepulcher Overlook", npc = "Ancient Translocator", x = 64.89, y = 53.55, faction = "B", continent = 1970 },
		{ name = "Sepulcher of the First Ones", npc = "Ancient Translocator", x = 73.00, y = 53.39, faction = "B", continent = 1970 },
		{ name = "Primus Locus", npc = "Locus Shift", x = 48.43, y = 26.35, faction = "B", continent = 1970 },
		{ name = "Secundus Locus", npc = "Locus Shift", x = 47.96, y = 27.91, faction = "B", continent = 1970 },
		{ name = "Tertius Locus", npc = "Locus Shift", x = 51.91, y = 27.11, faction = "B", continent = 1970 },
		{ name = "Quartus Locus", npc = "Locus Shift", x = 48.52, y = 29.70, faction = "B", continent = 1970 },
		{ name = "Quintus Locus", npc = "Locus Shift", x = 50.67, y = 32.60, faction = "B", continent = 1970 },
		{ name = "Ultimus Locus", npc = "Locus Shift", x = 48.89, y = 31.43, faction = "B", continent = 1970 },
	},
	["zul aman m"] = {
		{ name = "Amani'Zar Village", npc = "Eagletender Vikovu", x = 44.82, y = 65.43, faction = "B", continent = 13 },
		{ name = "Shadebasin Watch", npc = "Eagletender Ful'nac", x = 44.01, y = 33.61, faction = "B", continent = 13 },
		{ name = "Witherbark Bluffs", npc = "Eagletender Do'nac", x = 38.89, y = 23.21, faction = "B", continent = 13 },
		{ name = "Camp Stonewash", npc = "Scroll of Flight", x = 47.31, y = 25.52, faction = "B", continent = 13 },
		{ name = "Torntusk Overlook", npc = "Eagletender Tha'mon", x = 33.90, y = 78.32, faction = "B", continent = 13 },
	},
	["zul'drak"] = {
		{ name = "Light's Breach", npc = "Danica Saint", x = 32.18, y = 74.39, faction = "B", continent = 113 },
		{ name = "Ebon Watch", npc = "Baneflight", x = 14.01, y = 73.58, faction = "B", continent = 113 },
		{ name = "The Argent Stand", npc = " Gurric", x = 41.55, y = 64.43, faction = "B", continent = 113 },
		{ name = "Zim'Torga", npc = "Maaka", x = 60.04, y = 56.71, faction = "B", continent = 113 },
		{ name = "Gundrak", npc = "Rafae", x = 70.46, y = 23.28, faction = "B", continent = 113 },
	},
	["zuldazar"] = {
		{ name = "Zeb'ahari", npc = "Paku'ai Jasi", x = 77.36, y = 15.35, faction = "H", continent = 875 },
		{ name = "Warbeast Kraal", npc = "Paku'ai Verraki", x = 67.26, y = 43.03, faction = "H", continent = 875 },
		{ name = "Garden of the Loa", npc = "Paku'ai Rip'nata", x = 49.72, y = 26.27, faction = "H", continent = 875 },
		{ name = "Atal'dazar", npc = "Loz the Paku'ai", x = 46.17, y = 35.81, faction = "H", continent = 875 },
		{ name = "Temple of the Prophet", npc = "Kaza the Skyblade", x = 49.81, y = 44.59, faction = "H", continent = 875 },
		{ name = "Warport Rastari", npc = "Paku'ai Ja'nessa", x = 48.22, y = 60.34, faction = "H", continent = 875 },
		{ name = "Xibala", npc = "Eliara Duskwing", x = 44.84, y = 72.25, faction = "H", continent = 875 },
		{ name = "Isle of Fangs", npc = "Paku'ai Leti", x = 54.45, y = 87.06, faction = "H", continent = 875 },
		{ name = "Tusk Isle", npc = "Paku'ai Jetar", x = 59.39, y = 77.94, faction = "H", continent = 875 },
		{ name = "The Mugambala", npc = "Paku'ai Chal", x = 53.34, y = 57.33, faction = "H", continent = 875 },
		{ name = "Xibala", npc = "Paula Waverunner", x = 40.58, y = 71.45, faction = "A", continent = 875 },
		{ name = "Castaway Encampment", npc = "Kaolin", x = 77.66, y = 54.45, faction = "A", continent = 875 },
		{ name = "Veiled Grotto", npc = "Isaac \"Lefteye\" Bentham", x = 44.42, y = 36.83, faction = "A", continent = 875 },
		{ name = "Mistvine Ledge", npc = "Sornoth Slagmane", x = 64.33, y = 47.33, faction = "A", continent = 875 },
		{ name = "Mugamba Overlook", npc = "Drager Smokewing", x = 44.84, y = 27.07, faction = "A", continent = 875 },
		{ name = "Verdant Hollow", npc = "Kina Cobbleflame", x = 55.65, y = 24.85, faction = "A", continent = 875 },
		{ name = "Nesingwary's Gameland", npc = "Lasa the Galerider", x = 66.19, y = 17.60, faction = "B", continent = 875 },
		{ name = "Scaletrader Post", npc = "Scroll of Flight", x = 70.78, y = 29.60, faction = "B", continent = 875 },
		{ name = "Atal'Gral", npc = "Scroll of Flight", x = 79.97, y = 41.39, faction = "B", continent = 875 },
		{ name = "Seeker's Outpost", npc = "Scroll of Flight", x = 70.45, y = 65.31, faction = "B", continent = 875 },
	},
}
